<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: returns/v1/returns.proto

namespace Returns\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>returns.v1.GetReturnStatusResponse</code>
 */
class GetReturnStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string return_id = 2 [json_name = "returnId"];</code>
     */
    protected $return_id = '';
    /**
     * Generated from protobuf field <code>string order_id = 3 [json_name = "orderId"];</code>
     */
    protected $order_id = '';
    /**
     * Generated from protobuf field <code>.common.v1.ReturnStatus status = 4 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string reason = 5 [json_name = "reason"];</code>
     */
    protected $reason = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp resolved_at = 6 [json_name = "resolvedAt"];</code>
     */
    protected $resolved_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $return_id
     *     @type string $order_id
     *     @type int $status
     *     @type string $reason
     *     @type \Google\Protobuf\Timestamp $resolved_at
     * }
     */
    public function __construct($data = NULL) {
        \Returns\V1\GPBMetadata\Returns::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string return_id = 2 [json_name = "returnId"];</code>
     * @return string
     */
    public function getReturnId()
    {
        return $this->return_id;
    }

    /**
     * Generated from protobuf field <code>string return_id = 2 [json_name = "returnId"];</code>
     * @param string $var
     * @return $this
     */
    public function setReturnId($var)
    {
        GPBUtil::checkString($var, True);
        $this->return_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 3 [json_name = "orderId"];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 3 [json_name = "orderId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ReturnStatus status = 4 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ReturnStatus status = 4 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Common\V1\ReturnStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 5 [json_name = "reason"];</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 5 [json_name = "reason"];</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp resolved_at = 6 [json_name = "resolvedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getResolvedAt()
    {
        return $this->resolved_at;
    }

    public function hasResolvedAt()
    {
        return isset($this->resolved_at);
    }

    public function clearResolvedAt()
    {
        unset($this->resolved_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp resolved_at = 6 [json_name = "resolvedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setResolvedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->resolved_at = $var;

        return $this;
    }

}

