<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: returns/v1/returns.proto

namespace Returns\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>returns.v1.GetReturnStatusRequest</code>
 */
class GetReturnStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string return_id = 2 [json_name = "returnId"];</code>
     */
    protected $return_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $merchant_principal_id
     *     @type string $return_id
     * }
     */
    public function __construct($data = NULL) {
        \Returns\V1\GPBMetadata\Returns::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string return_id = 2 [json_name = "returnId"];</code>
     * @return string
     */
    public function getReturnId()
    {
        return $this->return_id;
    }

    /**
     * Generated from protobuf field <code>string return_id = 2 [json_name = "returnId"];</code>
     * @param string $var
     * @return $this
     */
    public function setReturnId($var)
    {
        GPBUtil::checkString($var, True);
        $this->return_id = $var;

        return $this;
    }

}

