<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shipping/v1/shipping.proto

namespace Shipping\V1\GPBMetadata;

class Shipping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Common\V1\GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBE\x08\x0A\x1Ashipping/v1/shipping.proto\x12\x0Bshipping.v1\"\xE6\x01\x0A\x1EEstimateShippingOptionsRequest\x12+\x0A\x06origin\x18\x01 \x01(\x0B2\x13.common.v1.GeoPointR\x06origin\x125\x0A\x0Bdestination\x18\x02 \x01(\x0B2\x13.common.v1.GeoPointR\x0Bdestination\x12,\x0A\x12total_weight_grams\x18\x03 \x01(\x03R\x10totalWeightGrams\x122\x0A\x15merchant_principal_id\x18\x04 \x01(\x09R\x13merchantPrincipalId\"\xBE\x02\x0A\x0DCourierOption\x12!\x0A\x0Cservice_tier\x18\x01 \x01(\x09R\x0BserviceTier\x12!\x0A\x0Cservice_name\x18\x02 \x01(\x09R\x0BserviceName\x12\x1F\x0A\x0Bdistance_km\x18\x03 \x01(\x01R\x0AdistanceKm\x12<\x0A\x11base_shipping_fee\x18\x04 \x01(\x0B2\x10.common.v1.MoneyR\x0FbaseShippingFee\x126\x0A\x17estimated_delivery_time\x18\x05 \x01(\x09R\x15estimatedDeliveryTime\x12!\x0A\x0Cis_available\x18\x06 \x01(\x08R\x0BisAvailable\x12-\x0A\x12unavailable_reason\x18\x07 \x01(\x09R\x11unavailableReason\"x\x0A\x1FEstimateShippingOptionsResponse\x12\x1F\x0A\x0Bdistance_km\x18\x01 \x01(\x01R\x0AdistanceKm\x124\x0A\x07options\x18\x02 \x03(\x0B2\x1A.shipping.v1.CourierOptionR\x07options2\x87\x01\x0A\x0FShippingService\x12t\x0A\x17EstimateShippingOptions\x12+.shipping.v1.EstimateShippingOptionsRequest\x1A,.shipping.v1.EstimateShippingOptionsResponseB\xDC\x01\x0A!com.kinetix.contracts.shipping.v1B\x0DShippingProtoP\x01ZIgithub.com/WildanFrananda/kinetix-contracts/gen/go/shipping/v1;shippingv1\xA2\x02\x03KNX\xAA\x02\x1DKinetix.Contracts.Shipping.V1\xCA\x02\x0BShipping\\V1\xE2\x02\x17Shipping\\V1\\GPBMetadata\xEA\x02\x0CShipping::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

