<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto

namespace Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.v1.ErrorDetail</code>
 */
class ErrorDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string error_code = 1 [json_name = "errorCode"];</code>
     */
    protected $error_code = '';
    /**
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>repeated string field_violations = 3 [json_name = "fieldViolations"];</code>
     */
    private $field_violations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $error_code
     *     @type string $message
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $field_violations
     * }
     */
    public function __construct($data = NULL) {
        \Common\V1\GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string error_code = 1 [json_name = "errorCode"];</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>string error_code = 1 [json_name = "errorCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string field_violations = 3 [json_name = "fieldViolations"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldViolations()
    {
        return $this->field_violations;
    }

    /**
     * Generated from protobuf field <code>repeated string field_violations = 3 [json_name = "fieldViolations"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldViolations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->field_violations = $arr;

        return $this;
    }

}

