<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto

namespace Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.v1.Money</code>
 */
class Money extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 amount_minor = 1 [json_name = "amountMinor"];</code>
     */
    protected $amount_minor = 0;
    /**
     * Generated from protobuf field <code>string currency = 2 [json_name = "currency"];</code>
     */
    protected $currency = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $amount_minor
     *     @type string $currency
     * }
     */
    public function __construct($data = NULL) {
        \Common\V1\GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 amount_minor = 1 [json_name = "amountMinor"];</code>
     * @return int|string
     */
    public function getAmountMinor()
    {
        return $this->amount_minor;
    }

    /**
     * Generated from protobuf field <code>int64 amount_minor = 1 [json_name = "amountMinor"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmountMinor($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount_minor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 2 [json_name = "currency"];</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 2 [json_name = "currency"];</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

}

