<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto

namespace Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.v1.OrderItem</code>
 */
class OrderItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sku = 1 [json_name = "sku"];</code>
     */
    protected $sku = '';
    /**
     * Generated from protobuf field <code>string product_name = 2 [json_name = "productName"];</code>
     */
    protected $product_name = '';
    /**
     * Generated from protobuf field <code>int32 quantity = 3 [json_name = "quantity"];</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>.common.v1.Money unit_price = 4 [json_name = "unitPrice"];</code>
     */
    protected $unit_price = null;
    /**
     * Generated from protobuf field <code>string bin_location = 5 [json_name = "binLocation"];</code>
     */
    protected $bin_location = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sku
     *     @type string $product_name
     *     @type int $quantity
     *     @type \Common\V1\Money $unit_price
     *     @type string $bin_location
     * }
     */
    public function __construct($data = NULL) {
        \Common\V1\GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sku = 1 [json_name = "sku"];</code>
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Generated from protobuf field <code>string sku = 1 [json_name = "sku"];</code>
     * @param string $var
     * @return $this
     */
    public function setSku($var)
    {
        GPBUtil::checkString($var, True);
        $this->sku = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_name = 2 [json_name = "productName"];</code>
     * @return string
     */
    public function getProductName()
    {
        return $this->product_name;
    }

    /**
     * Generated from protobuf field <code>string product_name = 2 [json_name = "productName"];</code>
     * @param string $var
     * @return $this
     */
    public function setProductName($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 3 [json_name = "quantity"];</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 3 [json_name = "quantity"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money unit_price = 4 [json_name = "unitPrice"];</code>
     * @return \Common\V1\Money|null
     */
    public function getUnitPrice()
    {
        return $this->unit_price;
    }

    public function hasUnitPrice()
    {
        return isset($this->unit_price);
    }

    public function clearUnitPrice()
    {
        unset($this->unit_price);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money unit_price = 4 [json_name = "unitPrice"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setUnitPrice($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->unit_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bin_location = 5 [json_name = "binLocation"];</code>
     * @return string
     */
    public function getBinLocation()
    {
        return $this->bin_location;
    }

    /**
     * Generated from protobuf field <code>string bin_location = 5 [json_name = "binLocation"];</code>
     * @param string $var
     * @return $this
     */
    public function setBinLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->bin_location = $var;

        return $this;
    }

}

