<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/fulfillment.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.CancelOrderResponse</code>
 */
class CancelOrderResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus current_status = 3 [json_name = "currentStatus"];</code>
     */
    protected $current_status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type string $message
     *     @type int $current_status
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Fulfillment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus current_status = 3 [json_name = "currentStatus"];</code>
     * @return int
     */
    public function getCurrentStatus()
    {
        return $this->current_status;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus current_status = 3 [json_name = "currentStatus"];</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentStatus($var)
    {
        GPBUtil::checkEnum($var, \Common\V1\OrderStatus::class);
        $this->current_status = $var;

        return $this;
    }

}

