<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/fulfillment.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.CheckBinStockResponse</code>
 */
class CheckBinStockResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string sku = 2 [json_name = "sku"];</code>
     */
    protected $sku = '';
    /**
     * Generated from protobuf field <code>string product_name = 3 [json_name = "productName"];</code>
     */
    protected $product_name = '';
    /**
     * Generated from protobuf field <code>int32 physical_stock = 4 [json_name = "physicalStock"];</code>
     */
    protected $physical_stock = 0;
    /**
     * Generated from protobuf field <code>int32 allocated_stock = 5 [json_name = "allocatedStock"];</code>
     */
    protected $allocated_stock = 0;
    /**
     * Generated from protobuf field <code>int32 available_stock = 6 [json_name = "availableStock"];</code>
     */
    protected $available_stock = 0;
    /**
     * Generated from protobuf field <code>string bin_location = 7 [json_name = "binLocation"];</code>
     */
    protected $bin_location = '';
    /**
     * Generated from protobuf field <code>bool low_stock_warning = 8 [json_name = "lowStockWarning"];</code>
     */
    protected $low_stock_warning = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $sku
     *     @type string $product_name
     *     @type int $physical_stock
     *     @type int $allocated_stock
     *     @type int $available_stock
     *     @type string $bin_location
     *     @type bool $low_stock_warning
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Fulfillment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sku = 2 [json_name = "sku"];</code>
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Generated from protobuf field <code>string sku = 2 [json_name = "sku"];</code>
     * @param string $var
     * @return $this
     */
    public function setSku($var)
    {
        GPBUtil::checkString($var, True);
        $this->sku = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_name = 3 [json_name = "productName"];</code>
     * @return string
     */
    public function getProductName()
    {
        return $this->product_name;
    }

    /**
     * Generated from protobuf field <code>string product_name = 3 [json_name = "productName"];</code>
     * @param string $var
     * @return $this
     */
    public function setProductName($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 physical_stock = 4 [json_name = "physicalStock"];</code>
     * @return int
     */
    public function getPhysicalStock()
    {
        return $this->physical_stock;
    }

    /**
     * Generated from protobuf field <code>int32 physical_stock = 4 [json_name = "physicalStock"];</code>
     * @param int $var
     * @return $this
     */
    public function setPhysicalStock($var)
    {
        GPBUtil::checkInt32($var);
        $this->physical_stock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 allocated_stock = 5 [json_name = "allocatedStock"];</code>
     * @return int
     */
    public function getAllocatedStock()
    {
        return $this->allocated_stock;
    }

    /**
     * Generated from protobuf field <code>int32 allocated_stock = 5 [json_name = "allocatedStock"];</code>
     * @param int $var
     * @return $this
     */
    public function setAllocatedStock($var)
    {
        GPBUtil::checkInt32($var);
        $this->allocated_stock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 available_stock = 6 [json_name = "availableStock"];</code>
     * @return int
     */
    public function getAvailableStock()
    {
        return $this->available_stock;
    }

    /**
     * Generated from protobuf field <code>int32 available_stock = 6 [json_name = "availableStock"];</code>
     * @param int $var
     * @return $this
     */
    public function setAvailableStock($var)
    {
        GPBUtil::checkInt32($var);
        $this->available_stock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bin_location = 7 [json_name = "binLocation"];</code>
     * @return string
     */
    public function getBinLocation()
    {
        return $this->bin_location;
    }

    /**
     * Generated from protobuf field <code>string bin_location = 7 [json_name = "binLocation"];</code>
     * @param string $var
     * @return $this
     */
    public function setBinLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->bin_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool low_stock_warning = 8 [json_name = "lowStockWarning"];</code>
     * @return bool
     */
    public function getLowStockWarning()
    {
        return $this->low_stock_warning;
    }

    /**
     * Generated from protobuf field <code>bool low_stock_warning = 8 [json_name = "lowStockWarning"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowStockWarning($var)
    {
        GPBUtil::checkBool($var);
        $this->low_stock_warning = $var;

        return $this;
    }

}

