<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/fulfillment.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.CreateOrderRequest</code>
 */
class CreateOrderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>.common.v1.Address pickup_address = 3 [json_name = "pickupAddress"];</code>
     */
    protected $pickup_address = null;
    /**
     * Generated from protobuf field <code>.common.v1.Address shipping_address = 4 [json_name = "shippingAddress"];</code>
     */
    protected $shipping_address = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money total_amount = 5 [json_name = "totalAmount"];</code>
     */
    protected $total_amount = null;
    /**
     * Generated from protobuf field <code>repeated .common.v1.OrderItem items = 6 [json_name = "items"];</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 7 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint pickup_location = 8 [json_name = "pickupLocation"];</code>
     */
    protected $pickup_location = null;
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint dropoff_location = 9 [json_name = "dropoffLocation"];</code>
     */
    protected $dropoff_location = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $merchant_principal_id
     *     @type string $order_number
     *     @type \Common\V1\Address $pickup_address
     *     @type \Common\V1\Address $shipping_address
     *     @type \Common\V1\Money $total_amount
     *     @type array<\Common\V1\OrderItem>|\Google\Protobuf\Internal\RepeatedField $items
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     *     @type \Common\V1\GeoPoint $pickup_location
     *     @type \Common\V1\GeoPoint $dropoff_location
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Fulfillment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address pickup_address = 3 [json_name = "pickupAddress"];</code>
     * @return \Common\V1\Address|null
     */
    public function getPickupAddress()
    {
        return $this->pickup_address;
    }

    public function hasPickupAddress()
    {
        return isset($this->pickup_address);
    }

    public function clearPickupAddress()
    {
        unset($this->pickup_address);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address pickup_address = 3 [json_name = "pickupAddress"];</code>
     * @param \Common\V1\Address $var
     * @return $this
     */
    public function setPickupAddress($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Address::class);
        $this->pickup_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address shipping_address = 4 [json_name = "shippingAddress"];</code>
     * @return \Common\V1\Address|null
     */
    public function getShippingAddress()
    {
        return $this->shipping_address;
    }

    public function hasShippingAddress()
    {
        return isset($this->shipping_address);
    }

    public function clearShippingAddress()
    {
        unset($this->shipping_address);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address shipping_address = 4 [json_name = "shippingAddress"];</code>
     * @param \Common\V1\Address $var
     * @return $this
     */
    public function setShippingAddress($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Address::class);
        $this->shipping_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_amount = 5 [json_name = "totalAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getTotalAmount()
    {
        return $this->total_amount;
    }

    public function hasTotalAmount()
    {
        return isset($this->total_amount);
    }

    public function clearTotalAmount()
    {
        unset($this->total_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_amount = 5 [json_name = "totalAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setTotalAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->total_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .common.v1.OrderItem items = 6 [json_name = "items"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .common.v1.OrderItem items = 6 [json_name = "items"];</code>
     * @param array<\Common\V1\OrderItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\V1\OrderItem::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 7 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 7 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint pickup_location = 8 [json_name = "pickupLocation"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getPickupLocation()
    {
        return $this->pickup_location;
    }

    public function hasPickupLocation()
    {
        return isset($this->pickup_location);
    }

    public function clearPickupLocation()
    {
        unset($this->pickup_location);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint pickup_location = 8 [json_name = "pickupLocation"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setPickupLocation($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->pickup_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint dropoff_location = 9 [json_name = "dropoffLocation"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getDropoffLocation()
    {
        return $this->dropoff_location;
    }

    public function hasDropoffLocation()
    {
        return isset($this->dropoff_location);
    }

    public function clearDropoffLocation()
    {
        unset($this->dropoff_location);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint dropoff_location = 9 [json_name = "dropoffLocation"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setDropoffLocation($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->dropoff_location = $var;

        return $this;
    }

}

