<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/task.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.CreateFulfillmentTaskResponse</code>
 */
class CreateFulfillmentTaskResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>string task_id = 2 [json_name = "taskId"];</code>
     */
    protected $task_id = '';
    /**
     * Generated from protobuf field <code>bool already_created = 3 [json_name = "alreadyCreated"];</code>
     */
    protected $already_created = false;
    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type string $task_id
     *     @type bool $already_created
     *     @type \Common\V1\ErrorDetail $error
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Task::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string task_id = 2 [json_name = "taskId"];</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>string task_id = 2 [json_name = "taskId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool already_created = 3 [json_name = "alreadyCreated"];</code>
     * @return bool
     */
    public function getAlreadyCreated()
    {
        return $this->already_created;
    }

    /**
     * Generated from protobuf field <code>bool already_created = 3 [json_name = "alreadyCreated"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyCreated($var)
    {
        GPBUtil::checkBool($var);
        $this->already_created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     * @return \Common\V1\ErrorDetail|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     * @param \Common\V1\ErrorDetail $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\ErrorDetail::class);
        $this->error = $var;

        return $this;
    }

}

