<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/fulfillment.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.GetOrderStatusResponse</code>
 */
class GetOrderStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     */
    protected $order_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 4 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string awb_number = 5 [json_name = "awbNumber"];</code>
     */
    protected $awb_number = '';
    /**
     * Generated from protobuf field <code>string pod_photo_url = 6 [json_name = "podPhotoUrl"];</code>
     */
    protected $pod_photo_url = '';
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint driver_location = 7 [json_name = "driverLocation"];</code>
     */
    protected $driver_location = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 8 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $order_id
     *     @type string $order_number
     *     @type int $status
     *     @type string $awb_number
     *     @type string $pod_photo_url
     *     @type \Common\V1\GeoPoint $driver_location
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Fulfillment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Common\V1\OrderStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string awb_number = 5 [json_name = "awbNumber"];</code>
     * @return string
     */
    public function getAwbNumber()
    {
        return $this->awb_number;
    }

    /**
     * Generated from protobuf field <code>string awb_number = 5 [json_name = "awbNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setAwbNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->awb_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pod_photo_url = 6 [json_name = "podPhotoUrl"];</code>
     * @return string
     */
    public function getPodPhotoUrl()
    {
        return $this->pod_photo_url;
    }

    /**
     * Generated from protobuf field <code>string pod_photo_url = 6 [json_name = "podPhotoUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setPodPhotoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->pod_photo_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint driver_location = 7 [json_name = "driverLocation"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getDriverLocation()
    {
        return $this->driver_location;
    }

    public function hasDriverLocation()
    {
        return isset($this->driver_location);
    }

    public function clearDriverLocation()
    {
        unset($this->driver_location);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint driver_location = 7 [json_name = "driverLocation"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setDriverLocation($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->driver_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 8 [json_name = "updatedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 8 [json_name = "updatedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

