<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/fulfillment.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.GetOrderStatusRequest</code>
 */
class GetOrderStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     */
    protected $order_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $merchant_principal_id
     *     @type string $order_id
     *     @type string $order_number
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Fulfillment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

}

