<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/task.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.RecordCourierAwbResponse</code>
 */
class RecordCourierAwbResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool accepted = 1 [json_name = "accepted"];</code>
     */
    protected $accepted = false;
    /**
     * Generated from protobuf field <code>bool already_recorded = 2 [json_name = "alreadyRecorded"];</code>
     */
    protected $already_recorded = false;
    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 3 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $accepted
     *     @type bool $already_recorded
     *     @type \Common\V1\ErrorDetail $error
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Task::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool accepted = 1 [json_name = "accepted"];</code>
     * @return bool
     */
    public function getAccepted()
    {
        return $this->accepted;
    }

    /**
     * Generated from protobuf field <code>bool accepted = 1 [json_name = "accepted"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAccepted($var)
    {
        GPBUtil::checkBool($var);
        $this->accepted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool already_recorded = 2 [json_name = "alreadyRecorded"];</code>
     * @return bool
     */
    public function getAlreadyRecorded()
    {
        return $this->already_recorded;
    }

    /**
     * Generated from protobuf field <code>bool already_recorded = 2 [json_name = "alreadyRecorded"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyRecorded($var)
    {
        GPBUtil::checkBool($var);
        $this->already_recorded = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 3 [json_name = "error"];</code>
     * @return \Common\V1\ErrorDetail|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 3 [json_name = "error"];</code>
     * @param \Common\V1\ErrorDetail $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\ErrorDetail::class);
        $this->error = $var;

        return $this;
    }

}

