<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/task.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.RecordCourierAwbRequest</code>
 */
class RecordCourierAwbRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string fulfillment_task_id = 2 [json_name = "fulfillmentTaskId"];</code>
     */
    protected $fulfillment_task_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>string awb_number = 4 [json_name = "awbNumber"];</code>
     */
    protected $awb_number = '';
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $merchant_principal_id
     *     @type string $fulfillment_task_id
     *     @type string $order_number
     *     @type string $awb_number
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Task::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fulfillment_task_id = 2 [json_name = "fulfillmentTaskId"];</code>
     * @return string
     */
    public function getFulfillmentTaskId()
    {
        return $this->fulfillment_task_id;
    }

    /**
     * Generated from protobuf field <code>string fulfillment_task_id = 2 [json_name = "fulfillmentTaskId"];</code>
     * @param string $var
     * @return $this
     */
    public function setFulfillmentTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fulfillment_task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string awb_number = 4 [json_name = "awbNumber"];</code>
     * @return string
     */
    public function getAwbNumber()
    {
        return $this->awb_number;
    }

    /**
     * Generated from protobuf field <code>string awb_number = 4 [json_name = "awbNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setAwbNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->awb_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

}

