<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/fulfillment.proto

namespace Fulfillment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fulfillment.v1.ReleaseStockResponse</code>
 */
class ReleaseStockResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>bool already_released = 2 [json_name = "alreadyReleased"];</code>
     */
    protected $already_released = false;
    /**
     * Generated from protobuf field <code>int32 remaining_available = 3 [json_name = "remainingAvailable"];</code>
     */
    protected $remaining_available = 0;
    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type bool $already_released
     *     @type int $remaining_available
     *     @type \Common\V1\ErrorDetail $error
     * }
     */
    public function __construct($data = NULL) {
        \Fulfillment\V1\GPBMetadata\Fulfillment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool already_released = 2 [json_name = "alreadyReleased"];</code>
     * @return bool
     */
    public function getAlreadyReleased()
    {
        return $this->already_released;
    }

    /**
     * Generated from protobuf field <code>bool already_released = 2 [json_name = "alreadyReleased"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyReleased($var)
    {
        GPBUtil::checkBool($var);
        $this->already_released = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 remaining_available = 3 [json_name = "remainingAvailable"];</code>
     * @return int
     */
    public function getRemainingAvailable()
    {
        return $this->remaining_available;
    }

    /**
     * Generated from protobuf field <code>int32 remaining_available = 3 [json_name = "remainingAvailable"];</code>
     * @param int $var
     * @return $this
     */
    public function setRemainingAvailable($var)
    {
        GPBUtil::checkInt32($var);
        $this->remaining_available = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     * @return \Common\V1\ErrorDetail|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     * @param \Common\V1\ErrorDetail $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\ErrorDetail::class);
        $this->error = $var;

        return $this;
    }

}

