<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/catalog.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>catalog.v1.ChangedSinceRequest</code>
 */
class ChangedSinceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.catalog.v1.Cursor cursor = 1 [json_name = "cursor"];</code>
     */
    protected $cursor = null;
    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Cursor $cursor
     *     @type int $limit
     * }
     */
    public function __construct($data = NULL) {
        \Catalog\V1\GPBMetadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Cursor cursor = 1 [json_name = "cursor"];</code>
     * @return \Catalog\V1\Cursor|null
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    public function hasCursor()
    {
        return isset($this->cursor);
    }

    public function clearCursor()
    {
        unset($this->cursor);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Cursor cursor = 1 [json_name = "cursor"];</code>
     * @param \Catalog\V1\Cursor $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkMessage($var, \Catalog\V1\Cursor::class);
        $this->cursor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

