<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/catalog.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>catalog.v1.Cursor</code>
 */
class Cursor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     */
    protected $updated_through = null;
    /**
     * Generated from protobuf field <code>string last_sku = 2 [json_name = "lastSku"];</code>
     */
    protected $last_sku = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $updated_through
     *     @type string $last_sku
     * }
     */
    public function __construct($data = NULL) {
        \Catalog\V1\GPBMetadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedThrough()
    {
        return $this->updated_through;
    }

    public function hasUpdatedThrough()
    {
        return isset($this->updated_through);
    }

    public function clearUpdatedThrough()
    {
        unset($this->updated_through);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedThrough($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_through = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_sku = 2 [json_name = "lastSku"];</code>
     * @return string
     */
    public function getLastSku()
    {
        return $this->last_sku;
    }

    /**
     * Generated from protobuf field <code>string last_sku = 2 [json_name = "lastSku"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastSku($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_sku = $var;

        return $this;
    }

}

