<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/catalog.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>catalog.v1.GetProductResponse</code>
 */
class GetProductResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>.catalog.v1.Product product = 2 [json_name = "product"];</code>
     */
    protected $product = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type \Catalog\V1\Product $product
     * }
     */
    public function __construct($data = NULL) {
        \Catalog\V1\GPBMetadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Product product = 2 [json_name = "product"];</code>
     * @return \Catalog\V1\Product|null
     */
    public function getProduct()
    {
        return $this->product;
    }

    public function hasProduct()
    {
        return isset($this->product);
    }

    public function clearProduct()
    {
        unset($this->product);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Product product = 2 [json_name = "product"];</code>
     * @param \Catalog\V1\Product $var
     * @return $this
     */
    public function setProduct($var)
    {
        GPBUtil::checkMessage($var, \Catalog\V1\Product::class);
        $this->product = $var;

        return $this;
    }

}

