<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/catalog.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>catalog.v1.Product</code>
 */
class Product extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sku = 1 [json_name = "sku"];</code>
     */
    protected $sku = '';
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string title = 3 [json_name = "title"];</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string description = 4 [json_name = "description"];</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.common.v1.Money price = 5 [json_name = "price"];</code>
     */
    protected $price = null;
    /**
     * Generated from protobuf field <code>string image_url = 6 [json_name = "imageUrl"];</code>
     */
    protected $image_url = '';
    /**
     * Generated from protobuf field <code>string category_slug = 7 [json_name = "categorySlug"];</code>
     */
    protected $category_slug = '';
    /**
     * Generated from protobuf field <code>string category_name = 8 [json_name = "categoryName"];</code>
     */
    protected $category_name = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sku
     *     @type string $merchant_principal_id
     *     @type string $title
     *     @type string $description
     *     @type \Common\V1\Money $price
     *     @type string $image_url
     *     @type string $category_slug
     *     @type string $category_name
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \Catalog\V1\GPBMetadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sku = 1 [json_name = "sku"];</code>
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Generated from protobuf field <code>string sku = 1 [json_name = "sku"];</code>
     * @param string $var
     * @return $this
     */
    public function setSku($var)
    {
        GPBUtil::checkString($var, True);
        $this->sku = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 3 [json_name = "title"];</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 3 [json_name = "title"];</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money price = 5 [json_name = "price"];</code>
     * @return \Common\V1\Money|null
     */
    public function getPrice()
    {
        return $this->price;
    }

    public function hasPrice()
    {
        return isset($this->price);
    }

    public function clearPrice()
    {
        unset($this->price);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money price = 5 [json_name = "price"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image_url = 6 [json_name = "imageUrl"];</code>
     * @return string
     */
    public function getImageUrl()
    {
        return $this->image_url;
    }

    /**
     * Generated from protobuf field <code>string image_url = 6 [json_name = "imageUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->image_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_slug = 7 [json_name = "categorySlug"];</code>
     * @return string
     */
    public function getCategorySlug()
    {
        return $this->category_slug;
    }

    /**
     * Generated from protobuf field <code>string category_slug = 7 [json_name = "categorySlug"];</code>
     * @param string $var
     * @return $this
     */
    public function setCategorySlug($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_slug = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_name = 8 [json_name = "categoryName"];</code>
     * @return string
     */
    public function getCategoryName()
    {
        return $this->category_name;
    }

    /**
     * Generated from protobuf field <code>string category_name = 8 [json_name = "categoryName"];</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

