<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shipping/v1/shipping.proto

namespace Shipping\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>shipping.v1.CourierOption</code>
 */
class CourierOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     */
    protected $service_tier = '';
    /**
     * Generated from protobuf field <code>string service_name = 2 [json_name = "serviceName"];</code>
     */
    protected $service_name = '';
    /**
     * Generated from protobuf field <code>double distance_km = 3 [json_name = "distanceKm"];</code>
     */
    protected $distance_km = 0.0;
    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 4 [json_name = "baseShippingFee"];</code>
     */
    protected $base_shipping_fee = null;
    /**
     * Generated from protobuf field <code>string estimated_delivery_time = 5 [json_name = "estimatedDeliveryTime"];</code>
     */
    protected $estimated_delivery_time = '';
    /**
     * Generated from protobuf field <code>bool is_available = 6 [json_name = "isAvailable"];</code>
     */
    protected $is_available = false;
    /**
     * Generated from protobuf field <code>string unavailable_reason = 7 [json_name = "unavailableReason"];</code>
     */
    protected $unavailable_reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service_tier
     *     @type string $service_name
     *     @type float $distance_km
     *     @type \Common\V1\Money $base_shipping_fee
     *     @type string $estimated_delivery_time
     *     @type bool $is_available
     *     @type string $unavailable_reason
     * }
     */
    public function __construct($data = NULL) {
        \Shipping\V1\GPBMetadata\Shipping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     * @return string
     */
    public function getServiceTier()
    {
        return $this->service_tier;
    }

    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceTier($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_tier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2 [json_name = "serviceName"];</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2 [json_name = "serviceName"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double distance_km = 3 [json_name = "distanceKm"];</code>
     * @return float
     */
    public function getDistanceKm()
    {
        return $this->distance_km;
    }

    /**
     * Generated from protobuf field <code>double distance_km = 3 [json_name = "distanceKm"];</code>
     * @param float $var
     * @return $this
     */
    public function setDistanceKm($var)
    {
        GPBUtil::checkDouble($var);
        $this->distance_km = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 4 [json_name = "baseShippingFee"];</code>
     * @return \Common\V1\Money|null
     */
    public function getBaseShippingFee()
    {
        return $this->base_shipping_fee;
    }

    public function hasBaseShippingFee()
    {
        return isset($this->base_shipping_fee);
    }

    public function clearBaseShippingFee()
    {
        unset($this->base_shipping_fee);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 4 [json_name = "baseShippingFee"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setBaseShippingFee($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->base_shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string estimated_delivery_time = 5 [json_name = "estimatedDeliveryTime"];</code>
     * @return string
     */
    public function getEstimatedDeliveryTime()
    {
        return $this->estimated_delivery_time;
    }

    /**
     * Generated from protobuf field <code>string estimated_delivery_time = 5 [json_name = "estimatedDeliveryTime"];</code>
     * @param string $var
     * @return $this
     */
    public function setEstimatedDeliveryTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->estimated_delivery_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_available = 6 [json_name = "isAvailable"];</code>
     * @return bool
     */
    public function getIsAvailable()
    {
        return $this->is_available;
    }

    /**
     * Generated from protobuf field <code>bool is_available = 6 [json_name = "isAvailable"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAvailable($var)
    {
        GPBUtil::checkBool($var);
        $this->is_available = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unavailable_reason = 7 [json_name = "unavailableReason"];</code>
     * @return string
     */
    public function getUnavailableReason()
    {
        return $this->unavailable_reason;
    }

    /**
     * Generated from protobuf field <code>string unavailable_reason = 7 [json_name = "unavailableReason"];</code>
     * @param string $var
     * @return $this
     */
    public function setUnavailableReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->unavailable_reason = $var;

        return $this;
    }

}

