<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shipping/v1/shipping.proto

namespace Shipping\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>shipping.v1.EstimateShippingOptionsResponse</code>
 */
class EstimateShippingOptionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double distance_km = 1 [json_name = "distanceKm"];</code>
     */
    protected $distance_km = 0.0;
    /**
     * Generated from protobuf field <code>repeated .shipping.v1.CourierOption options = 2 [json_name = "options"];</code>
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $distance_km
     *     @type array<\Shipping\V1\CourierOption>|\Google\Protobuf\Internal\RepeatedField $options
     * }
     */
    public function __construct($data = NULL) {
        \Shipping\V1\GPBMetadata\Shipping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double distance_km = 1 [json_name = "distanceKm"];</code>
     * @return float
     */
    public function getDistanceKm()
    {
        return $this->distance_km;
    }

    /**
     * Generated from protobuf field <code>double distance_km = 1 [json_name = "distanceKm"];</code>
     * @param float $var
     * @return $this
     */
    public function setDistanceKm($var)
    {
        GPBUtil::checkDouble($var);
        $this->distance_km = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .shipping.v1.CourierOption options = 2 [json_name = "options"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>repeated .shipping.v1.CourierOption options = 2 [json_name = "options"];</code>
     * @param array<\Shipping\V1\CourierOption>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shipping\V1\CourierOption::class);
        $this->options = $arr;

        return $this;
    }

}

