<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shipping/v1/shipping.proto

namespace Shipping\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>shipping.v1.EstimateShippingOptionsRequest</code>
 */
class EstimateShippingOptionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint origin = 1 [json_name = "origin"];</code>
     */
    protected $origin = null;
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint destination = 2 [json_name = "destination"];</code>
     */
    protected $destination = null;
    /**
     * Generated from protobuf field <code>int64 total_weight_grams = 3 [json_name = "totalWeightGrams"];</code>
     */
    protected $total_weight_grams = 0;
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 4 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Common\V1\GeoPoint $origin
     *     @type \Common\V1\GeoPoint $destination
     *     @type int|string $total_weight_grams
     *     @type string $merchant_principal_id
     * }
     */
    public function __construct($data = NULL) {
        \Shipping\V1\GPBMetadata\Shipping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint origin = 1 [json_name = "origin"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    public function hasOrigin()
    {
        return isset($this->origin);
    }

    public function clearOrigin()
    {
        unset($this->origin);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint origin = 1 [json_name = "origin"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->origin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint destination = 2 [json_name = "destination"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getDestination()
    {
        return $this->destination;
    }

    public function hasDestination()
    {
        return isset($this->destination);
    }

    public function clearDestination()
    {
        unset($this->destination);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint destination = 2 [json_name = "destination"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setDestination($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->destination = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_weight_grams = 3 [json_name = "totalWeightGrams"];</code>
     * @return int|string
     */
    public function getTotalWeightGrams()
    {
        return $this->total_weight_grams;
    }

    /**
     * Generated from protobuf field <code>int64 total_weight_grams = 3 [json_name = "totalWeightGrams"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWeightGrams($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_weight_grams = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 4 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 4 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

}

