<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/registry.proto

namespace Fleet\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fleet.v1.ActivateDriverResponse</code>
 */
class ActivateDriverResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>int64 driver_id = 2 [json_name = "driverId"];</code>
     */
    protected $driver_id = 0;
    /**
     * Generated from protobuf field <code>bool already_active = 3 [json_name = "alreadyActive"];</code>
     */
    protected $already_active = false;
    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type int|string $driver_id
     *     @type bool $already_active
     *     @type \Common\V1\ErrorDetail $error
     * }
     */
    public function __construct($data = NULL) {
        \Fleet\V1\GPBMetadata\Registry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 driver_id = 2 [json_name = "driverId"];</code>
     * @return int|string
     */
    public function getDriverId()
    {
        return $this->driver_id;
    }

    /**
     * Generated from protobuf field <code>int64 driver_id = 2 [json_name = "driverId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDriverId($var)
    {
        GPBUtil::checkInt64($var);
        $this->driver_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool already_active = 3 [json_name = "alreadyActive"];</code>
     * @return bool
     */
    public function getAlreadyActive()
    {
        return $this->already_active;
    }

    /**
     * Generated from protobuf field <code>bool already_active = 3 [json_name = "alreadyActive"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyActive($var)
    {
        GPBUtil::checkBool($var);
        $this->already_active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     * @return \Common\V1\ErrorDetail|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 4 [json_name = "error"];</code>
     * @param \Common\V1\ErrorDetail $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\ErrorDetail::class);
        $this->error = $var;

        return $this;
    }

}

