<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/fleet.proto

namespace Fleet\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fleet.v1.DispatchCourierRequest</code>
 */
class DispatchCourierRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     */
    protected $order_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>.common.v1.Address pickup_address = 4 [json_name = "pickupAddress", deprecated = true];</code>
     * @deprecated
     */
    protected $pickup_address = null;
    /**
     * Generated from protobuf field <code>.common.v1.Address delivery_address = 5 [json_name = "deliveryAddress", deprecated = true];</code>
     * @deprecated
     */
    protected $delivery_address = null;
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 6 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint pickup_point = 7 [json_name = "pickupPoint"];</code>
     */
    protected $pickup_point = null;
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint delivery_point = 8 [json_name = "deliveryPoint"];</code>
     */
    protected $delivery_point = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $merchant_principal_id
     *     @type string $order_id
     *     @type string $order_number
     *     @type \Common\V1\Address $pickup_address
     *     @type \Common\V1\Address $delivery_address
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     *     @type \Common\V1\GeoPoint $pickup_point
     *     @type \Common\V1\GeoPoint $delivery_point
     * }
     */
    public function __construct($data = NULL) {
        \Fleet\V1\GPBMetadata\Fleet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address pickup_address = 4 [json_name = "pickupAddress", deprecated = true];</code>
     * @return \Common\V1\Address|null
     * @deprecated
     */
    public function getPickupAddress()
    {
        if (isset($this->pickup_address)) {
            @trigger_error('pickup_address is deprecated.', E_USER_DEPRECATED);
        }
        return $this->pickup_address;
    }

    public function hasPickupAddress()
    {
        if (isset($this->pickup_address)) {
            @trigger_error('pickup_address is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->pickup_address);
    }

    public function clearPickupAddress()
    {
        @trigger_error('pickup_address is deprecated.', E_USER_DEPRECATED);
        unset($this->pickup_address);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address pickup_address = 4 [json_name = "pickupAddress", deprecated = true];</code>
     * @param \Common\V1\Address $var
     * @return $this
     * @deprecated
     */
    public function setPickupAddress($var)
    {
        @trigger_error('pickup_address is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \Common\V1\Address::class);
        $this->pickup_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address delivery_address = 5 [json_name = "deliveryAddress", deprecated = true];</code>
     * @return \Common\V1\Address|null
     * @deprecated
     */
    public function getDeliveryAddress()
    {
        if (isset($this->delivery_address)) {
            @trigger_error('delivery_address is deprecated.', E_USER_DEPRECATED);
        }
        return $this->delivery_address;
    }

    public function hasDeliveryAddress()
    {
        if (isset($this->delivery_address)) {
            @trigger_error('delivery_address is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->delivery_address);
    }

    public function clearDeliveryAddress()
    {
        @trigger_error('delivery_address is deprecated.', E_USER_DEPRECATED);
        unset($this->delivery_address);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address delivery_address = 5 [json_name = "deliveryAddress", deprecated = true];</code>
     * @param \Common\V1\Address $var
     * @return $this
     * @deprecated
     */
    public function setDeliveryAddress($var)
    {
        @trigger_error('delivery_address is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \Common\V1\Address::class);
        $this->delivery_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 6 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 6 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint pickup_point = 7 [json_name = "pickupPoint"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getPickupPoint()
    {
        return $this->pickup_point;
    }

    public function hasPickupPoint()
    {
        return isset($this->pickup_point);
    }

    public function clearPickupPoint()
    {
        unset($this->pickup_point);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint pickup_point = 7 [json_name = "pickupPoint"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setPickupPoint($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->pickup_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint delivery_point = 8 [json_name = "deliveryPoint"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getDeliveryPoint()
    {
        return $this->delivery_point;
    }

    public function hasDeliveryPoint()
    {
        return isset($this->delivery_point);
    }

    public function clearDeliveryPoint()
    {
        unset($this->delivery_point);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint delivery_point = 8 [json_name = "deliveryPoint"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setDeliveryPoint($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->delivery_point = $var;

        return $this;
    }

}

