<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/fleet.proto

namespace Fleet\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fleet.v1.DispatchCourierResponse</code>
 */
class DispatchCourierResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>string dispatch_ref = 2 [json_name = "dispatchRef"];</code>
     */
    protected $dispatch_ref = '';
    /**
     * Generated from protobuf field <code>string assigned_driver_principal_id = 3 [json_name = "assignedDriverPrincipalId"];</code>
     */
    protected $assigned_driver_principal_id = '';
    /**
     * Generated from protobuf field <code>string assigned_driver_name = 4 [json_name = "assignedDriverName"];</code>
     */
    protected $assigned_driver_name = '';
    /**
     * Generated from protobuf field <code>string assigned_driver_phone = 5 [json_name = "assignedDriverPhone"];</code>
     */
    protected $assigned_driver_phone = '';
    /**
     * Generated from protobuf field <code>string vehicle = 6 [json_name = "vehicle"];</code>
     */
    protected $vehicle = '';
    /**
     * Generated from protobuf field <code>int32 eta_minutes = 7 [json_name = "etaMinutes"];</code>
     */
    protected $eta_minutes = 0;
    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 8 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type string $dispatch_ref
     *     @type string $assigned_driver_principal_id
     *     @type string $assigned_driver_name
     *     @type string $assigned_driver_phone
     *     @type string $vehicle
     *     @type int $eta_minutes
     *     @type \Common\V1\ErrorDetail $error
     * }
     */
    public function __construct($data = NULL) {
        \Fleet\V1\GPBMetadata\Fleet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dispatch_ref = 2 [json_name = "dispatchRef"];</code>
     * @return string
     */
    public function getDispatchRef()
    {
        return $this->dispatch_ref;
    }

    /**
     * Generated from protobuf field <code>string dispatch_ref = 2 [json_name = "dispatchRef"];</code>
     * @param string $var
     * @return $this
     */
    public function setDispatchRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->dispatch_ref = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assigned_driver_principal_id = 3 [json_name = "assignedDriverPrincipalId"];</code>
     * @return string
     */
    public function getAssignedDriverPrincipalId()
    {
        return $this->assigned_driver_principal_id;
    }

    /**
     * Generated from protobuf field <code>string assigned_driver_principal_id = 3 [json_name = "assignedDriverPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssignedDriverPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->assigned_driver_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assigned_driver_name = 4 [json_name = "assignedDriverName"];</code>
     * @return string
     */
    public function getAssignedDriverName()
    {
        return $this->assigned_driver_name;
    }

    /**
     * Generated from protobuf field <code>string assigned_driver_name = 4 [json_name = "assignedDriverName"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssignedDriverName($var)
    {
        GPBUtil::checkString($var, True);
        $this->assigned_driver_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assigned_driver_phone = 5 [json_name = "assignedDriverPhone"];</code>
     * @return string
     */
    public function getAssignedDriverPhone()
    {
        return $this->assigned_driver_phone;
    }

    /**
     * Generated from protobuf field <code>string assigned_driver_phone = 5 [json_name = "assignedDriverPhone"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssignedDriverPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->assigned_driver_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vehicle = 6 [json_name = "vehicle"];</code>
     * @return string
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    /**
     * Generated from protobuf field <code>string vehicle = 6 [json_name = "vehicle"];</code>
     * @param string $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkString($var, True);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 eta_minutes = 7 [json_name = "etaMinutes"];</code>
     * @return int
     */
    public function getEtaMinutes()
    {
        return $this->eta_minutes;
    }

    /**
     * Generated from protobuf field <code>int32 eta_minutes = 7 [json_name = "etaMinutes"];</code>
     * @param int $var
     * @return $this
     */
    public function setEtaMinutes($var)
    {
        GPBUtil::checkInt32($var);
        $this->eta_minutes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 8 [json_name = "error"];</code>
     * @return \Common\V1\ErrorDetail|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 8 [json_name = "error"];</code>
     * @param \Common\V1\ErrorDetail $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\ErrorDetail::class);
        $this->error = $var;

        return $this;
    }

}

