<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/fleet.proto

namespace Fleet\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fleet.v1.DriverLocationPing</code>
 */
class DriverLocationPing extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string driver_principal_id = 1 [json_name = "driverPrincipalId"];</code>
     */
    protected $driver_principal_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint location = 3 [json_name = "location"];</code>
     */
    protected $location = null;
    /**
     * Generated from protobuf field <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
     */
    protected $speed_kmh = 0.0;
    /**
     * Generated from protobuf field <code>.common.v1.CourierStatus status = 5 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp observed_at = 6 [json_name = "observedAt"];</code>
     */
    protected $observed_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $driver_principal_id
     *     @type string $order_number
     *     @type \Common\V1\GeoPoint $location
     *     @type float $speed_kmh
     *     @type int $status
     *     @type \Google\Protobuf\Timestamp $observed_at
     * }
     */
    public function __construct($data = NULL) {
        \Fleet\V1\GPBMetadata\Fleet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 1 [json_name = "driverPrincipalId"];</code>
     * @return string
     */
    public function getDriverPrincipalId()
    {
        return $this->driver_principal_id;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 1 [json_name = "driverPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDriverPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint location = 3 [json_name = "location"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    public function hasLocation()
    {
        return isset($this->location);
    }

    public function clearLocation()
    {
        unset($this->location);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint location = 3 [json_name = "location"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
     * @return float
     */
    public function getSpeedKmh()
    {
        return $this->speed_kmh;
    }

    /**
     * Generated from protobuf field <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
     * @param float $var
     * @return $this
     */
    public function setSpeedKmh($var)
    {
        GPBUtil::checkDouble($var);
        $this->speed_kmh = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.CourierStatus status = 5 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.common.v1.CourierStatus status = 5 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Common\V1\CourierStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp observed_at = 6 [json_name = "observedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getObservedAt()
    {
        return $this->observed_at;
    }

    public function hasObservedAt()
    {
        return isset($this->observed_at);
    }

    public function clearObservedAt()
    {
        unset($this->observed_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp observed_at = 6 [json_name = "observedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setObservedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->observed_at = $var;

        return $this;
    }

}

