<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/fleet.proto

namespace Fleet\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fleet.v1.DriverLocationAck</code>
 */
class DriverLocationAck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string driver_principal_id = 1 [json_name = "driverPrincipalId"];</code>
     */
    protected $driver_principal_id = '';
    /**
     * Generated from protobuf field <code>bool received = 2 [json_name = "received"];</code>
     */
    protected $received = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp server_time = 3 [json_name = "serverTime"];</code>
     */
    protected $server_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $driver_principal_id
     *     @type bool $received
     *     @type \Google\Protobuf\Timestamp $server_time
     * }
     */
    public function __construct($data = NULL) {
        \Fleet\V1\GPBMetadata\Fleet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 1 [json_name = "driverPrincipalId"];</code>
     * @return string
     */
    public function getDriverPrincipalId()
    {
        return $this->driver_principal_id;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 1 [json_name = "driverPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDriverPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool received = 2 [json_name = "received"];</code>
     * @return bool
     */
    public function getReceived()
    {
        return $this->received;
    }

    /**
     * Generated from protobuf field <code>bool received = 2 [json_name = "received"];</code>
     * @param bool $var
     * @return $this
     */
    public function setReceived($var)
    {
        GPBUtil::checkBool($var);
        $this->received = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp server_time = 3 [json_name = "serverTime"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getServerTime()
    {
        return $this->server_time;
    }

    public function hasServerTime()
    {
        return isset($this->server_time);
    }

    public function clearServerTime()
    {
        unset($this->server_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp server_time = 3 [json_name = "serverTime"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setServerTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->server_time = $var;

        return $this;
    }

}

