<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/registry.proto

namespace Fleet\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fleet.v1.RegisterDriverRequest</code>
 */
class RegisterDriverRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     */
    protected $principal_id = '';
    /**
     * Generated from protobuf field <code>string vehicle_plate = 2 [json_name = "vehiclePlate"];</code>
     */
    protected $vehicle_plate = '';
    /**
     * Generated from protobuf field <code>int32 capacity_kg = 3 [json_name = "capacityKg"];</code>
     */
    protected $capacity_kg = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $principal_id
     *     @type string $vehicle_plate
     *     @type int $capacity_kg
     * }
     */
    public function __construct($data = NULL) {
        \Fleet\V1\GPBMetadata\Registry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @return string
     */
    public function getPrincipalId()
    {
        return $this->principal_id;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vehicle_plate = 2 [json_name = "vehiclePlate"];</code>
     * @return string
     */
    public function getVehiclePlate()
    {
        return $this->vehicle_plate;
    }

    /**
     * Generated from protobuf field <code>string vehicle_plate = 2 [json_name = "vehiclePlate"];</code>
     * @param string $var
     * @return $this
     */
    public function setVehiclePlate($var)
    {
        GPBUtil::checkString($var, True);
        $this->vehicle_plate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 capacity_kg = 3 [json_name = "capacityKg"];</code>
     * @return int
     */
    public function getCapacityKg()
    {
        return $this->capacity_kg;
    }

    /**
     * Generated from protobuf field <code>int32 capacity_kg = 3 [json_name = "capacityKg"];</code>
     * @param int $var
     * @return $this
     */
    public function setCapacityKg($var)
    {
        GPBUtil::checkInt32($var);
        $this->capacity_kg = $var;

        return $this;
    }

}

