<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.FulfillmentPackedRequest</code>
 */
class FulfillmentPackedRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>string fulfillment_task_id = 3 [json_name = "fulfillmentTaskId"];</code>
     */
    protected $fulfillment_task_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $merchant_principal_id
     *     @type string $order_number
     *     @type string $fulfillment_task_id
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 1 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fulfillment_task_id = 3 [json_name = "fulfillmentTaskId"];</code>
     * @return string
     */
    public function getFulfillmentTaskId()
    {
        return $this->fulfillment_task_id;
    }

    /**
     * Generated from protobuf field <code>string fulfillment_task_id = 3 [json_name = "fulfillmentTaskId"];</code>
     * @param string $var
     * @return $this
     */
    public function setFulfillmentTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fulfillment_task_id = $var;

        return $this;
    }

}

