<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.GetOrderDetailsResponse</code>
 */
class GetOrderDetailsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     */
    protected $order_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>string customer_principal_id = 4 [json_name = "customerPrincipalId"];</code>
     */
    protected $customer_principal_id = '';
    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 5 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>.common.v1.Money subtotal = 6 [json_name = "subtotal"];</code>
     */
    protected $subtotal = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money discount_amount = 7 [json_name = "discountAmount"];</code>
     */
    protected $discount_amount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee = 8 [json_name = "shippingFee"];</code>
     */
    protected $shipping_fee = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money final_total = 9 [json_name = "finalTotal"];</code>
     */
    protected $final_total = null;
    /**
     * Generated from protobuf field <code>repeated .order.v1.OrderLine lines = 10 [json_name = "lines"];</code>
     */
    private $lines;
    /**
     * Generated from protobuf field <code>.common.v1.Address shipping_address = 11 [json_name = "shippingAddress"];</code>
     */
    protected $shipping_address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $order_id
     *     @type string $order_number
     *     @type string $customer_principal_id
     *     @type int $status
     *     @type \Common\V1\Money $subtotal
     *     @type \Common\V1\Money $discount_amount
     *     @type \Common\V1\Money $shipping_fee
     *     @type \Common\V1\Money $final_total
     *     @type array<\Order\V1\OrderLine>|\Google\Protobuf\Internal\RepeatedField $lines
     *     @type \Common\V1\Address $shipping_address
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2 [json_name = "orderId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_principal_id = 4 [json_name = "customerPrincipalId"];</code>
     * @return string
     */
    public function getCustomerPrincipalId()
    {
        return $this->customer_principal_id;
    }

    /**
     * Generated from protobuf field <code>string customer_principal_id = 4 [json_name = "customerPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 5 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 5 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Common\V1\OrderStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money subtotal = 6 [json_name = "subtotal"];</code>
     * @return \Common\V1\Money|null
     */
    public function getSubtotal()
    {
        return $this->subtotal;
    }

    public function hasSubtotal()
    {
        return isset($this->subtotal);
    }

    public function clearSubtotal()
    {
        unset($this->subtotal);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money subtotal = 6 [json_name = "subtotal"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setSubtotal($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->subtotal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money discount_amount = 7 [json_name = "discountAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getDiscountAmount()
    {
        return $this->discount_amount;
    }

    public function hasDiscountAmount()
    {
        return isset($this->discount_amount);
    }

    public function clearDiscountAmount()
    {
        unset($this->discount_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money discount_amount = 7 [json_name = "discountAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setDiscountAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->discount_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee = 8 [json_name = "shippingFee"];</code>
     * @return \Common\V1\Money|null
     */
    public function getShippingFee()
    {
        return $this->shipping_fee;
    }

    public function hasShippingFee()
    {
        return isset($this->shipping_fee);
    }

    public function clearShippingFee()
    {
        unset($this->shipping_fee);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee = 8 [json_name = "shippingFee"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setShippingFee($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_total = 9 [json_name = "finalTotal"];</code>
     * @return \Common\V1\Money|null
     */
    public function getFinalTotal()
    {
        return $this->final_total;
    }

    public function hasFinalTotal()
    {
        return isset($this->final_total);
    }

    public function clearFinalTotal()
    {
        unset($this->final_total);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_total = 9 [json_name = "finalTotal"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setFinalTotal($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->final_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .order.v1.OrderLine lines = 10 [json_name = "lines"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLines()
    {
        return $this->lines;
    }

    /**
     * Generated from protobuf field <code>repeated .order.v1.OrderLine lines = 10 [json_name = "lines"];</code>
     * @param array<\Order\V1\OrderLine>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Order\V1\OrderLine::class);
        $this->lines = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address shipping_address = 11 [json_name = "shippingAddress"];</code>
     * @return \Common\V1\Address|null
     */
    public function getShippingAddress()
    {
        return $this->shipping_address;
    }

    public function hasShippingAddress()
    {
        return isset($this->shipping_address);
    }

    public function clearShippingAddress()
    {
        unset($this->shipping_address);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address shipping_address = 11 [json_name = "shippingAddress"];</code>
     * @param \Common\V1\Address $var
     * @return $this
     */
    public function setShippingAddress($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Address::class);
        $this->shipping_address = $var;

        return $this;
    }

}

