<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.ListOrdersForPrincipalRequest</code>
 */
class ListOrdersForPrincipalRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     */
    protected $principal_id = '';
    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 2 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int32 page = 3 [json_name = "page"];</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int32 page_size = 4 [json_name = "pageSize"];</code>
     */
    protected $page_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $principal_id
     *     @type int $status
     *     @type int $page
     *     @type int $page_size
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @return string
     */
    public function getPrincipalId()
    {
        return $this->principal_id;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 2 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 2 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Common\V1\OrderStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3 [json_name = "page"];</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3 [json_name = "page"];</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 4 [json_name = "pageSize"];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 4 [json_name = "pageSize"];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

}

