<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.OrderDeliveredRequest</code>
 */
class OrderDeliveredRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>string driver_principal_id = 2 [json_name = "driverPrincipalId"];</code>
     */
    protected $driver_principal_id = '';
    /**
     * Generated from protobuf field <code>string delivered_at = 3 [json_name = "deliveredAt"];</code>
     */
    protected $delivered_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $order_number
     *     @type string $driver_principal_id
     *     @type string $delivered_at
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 2 [json_name = "driverPrincipalId"];</code>
     * @return string
     */
    public function getDriverPrincipalId()
    {
        return $this->driver_principal_id;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 2 [json_name = "driverPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDriverPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string delivered_at = 3 [json_name = "deliveredAt"];</code>
     * @return string
     */
    public function getDeliveredAt()
    {
        return $this->delivered_at;
    }

    /**
     * Generated from protobuf field <code>string delivered_at = 3 [json_name = "deliveredAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeliveredAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->delivered_at = $var;

        return $this;
    }

}

