<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.OrdersChangedSinceRequest</code>
 */
class OrdersChangedSinceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.order.v1.OrderCursor cursor = 1 [json_name = "cursor"];</code>
     */
    protected $cursor = null;
    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Order\V1\OrderCursor $cursor
     *     @type int $limit
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.order.v1.OrderCursor cursor = 1 [json_name = "cursor"];</code>
     * @return \Order\V1\OrderCursor|null
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    public function hasCursor()
    {
        return isset($this->cursor);
    }

    public function clearCursor()
    {
        unset($this->cursor);
    }

    /**
     * Generated from protobuf field <code>.order.v1.OrderCursor cursor = 1 [json_name = "cursor"];</code>
     * @param \Order\V1\OrderCursor $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkMessage($var, \Order\V1\OrderCursor::class);
        $this->cursor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

