<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.OrderCursor</code>
 */
class OrderCursor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     */
    protected $updated_through = null;
    /**
     * Generated from protobuf field <code>string last_order_number = 2 [json_name = "lastOrderNumber"];</code>
     */
    protected $last_order_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $updated_through
     *     @type string $last_order_number
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedThrough()
    {
        return $this->updated_through;
    }

    public function hasUpdatedThrough()
    {
        return isset($this->updated_through);
    }

    public function clearUpdatedThrough()
    {
        unset($this->updated_through);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedThrough($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_through = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_order_number = 2 [json_name = "lastOrderNumber"];</code>
     * @return string
     */
    public function getLastOrderNumber()
    {
        return $this->last_order_number;
    }

    /**
     * Generated from protobuf field <code>string last_order_number = 2 [json_name = "lastOrderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_order_number = $var;

        return $this;
    }

}

