<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.OrderRecord</code>
 */
class OrderRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>string buyer_principal_id = 2 [json_name = "buyerPrincipalId"];</code>
     */
    protected $buyer_principal_id = '';
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 4 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>repeated string line_titles = 5 [json_name = "lineTitles"];</code>
     */
    private $line_titles;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp placed_at = 6 [json_name = "placedAt"];</code>
     */
    protected $placed_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $order_number
     *     @type string $buyer_principal_id
     *     @type string $merchant_principal_id
     *     @type int $status
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $line_titles
     *     @type \Google\Protobuf\Timestamp $placed_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string buyer_principal_id = 2 [json_name = "buyerPrincipalId"];</code>
     * @return string
     */
    public function getBuyerPrincipalId()
    {
        return $this->buyer_principal_id;
    }

    /**
     * Generated from protobuf field <code>string buyer_principal_id = 2 [json_name = "buyerPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.common.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Common\V1\OrderStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string line_titles = 5 [json_name = "lineTitles"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLineTitles()
    {
        return $this->line_titles;
    }

    /**
     * Generated from protobuf field <code>repeated string line_titles = 5 [json_name = "lineTitles"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLineTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->line_titles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp placed_at = 6 [json_name = "placedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getPlacedAt()
    {
        return $this->placed_at;
    }

    public function hasPlacedAt()
    {
        return isset($this->placed_at);
    }

    public function clearPlacedAt()
    {
        unset($this->placed_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp placed_at = 6 [json_name = "placedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setPlacedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->placed_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 7 [json_name = "updatedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

