<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.v1.ReturnGoodsReceivedRequest</code>
 */
class ReturnGoodsReceivedRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string return_number = 1 [json_name = "returnNumber"];</code>
     */
    protected $return_number = '';
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>repeated .order.v1.ReturnedLine lines = 3 [json_name = "lines"];</code>
     */
    private $lines;
    /**
     * Generated from protobuf field <code>string bin_code = 4 [json_name = "binCode"];</code>
     */
    protected $bin_code = '';
    /**
     * Generated from protobuf field <code>string received_at = 5 [json_name = "receivedAt"];</code>
     */
    protected $received_at = '';
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 6 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $return_number
     *     @type string $merchant_principal_id
     *     @type array<\Order\V1\ReturnedLine>|\Google\Protobuf\Internal\RepeatedField $lines
     *     @type string $bin_code
     *     @type string $received_at
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \Order\V1\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string return_number = 1 [json_name = "returnNumber"];</code>
     * @return string
     */
    public function getReturnNumber()
    {
        return $this->return_number;
    }

    /**
     * Generated from protobuf field <code>string return_number = 1 [json_name = "returnNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setReturnNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->return_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .order.v1.ReturnedLine lines = 3 [json_name = "lines"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLines()
    {
        return $this->lines;
    }

    /**
     * Generated from protobuf field <code>repeated .order.v1.ReturnedLine lines = 3 [json_name = "lines"];</code>
     * @param array<\Order\V1\ReturnedLine>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Order\V1\ReturnedLine::class);
        $this->lines = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bin_code = 4 [json_name = "binCode"];</code>
     * @return string
     */
    public function getBinCode()
    {
        return $this->bin_code;
    }

    /**
     * Generated from protobuf field <code>string bin_code = 4 [json_name = "binCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setBinCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->bin_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string received_at = 5 [json_name = "receivedAt"];</code>
     * @return string
     */
    public function getReceivedAt()
    {
        return $this->received_at;
    }

    /**
     * Generated from protobuf field <code>string received_at = 5 [json_name = "receivedAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setReceivedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->received_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 6 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 6 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

}

