<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order.proto

namespace Order\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>order.v1.ReturnStatus</code>
 */
class ReturnStatus
{
    /**
     * Generated from protobuf enum <code>RETURN_STATUS_UNSPECIFIED = 0;</code>
     */
    const RETURN_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>RETURN_STATUS_OPEN = 1;</code>
     */
    const RETURN_STATUS_OPEN = 1;
    /**
     * Generated from protobuf enum <code>RETURN_STATUS_GOODS_RECEIVED = 2;</code>
     */
    const RETURN_STATUS_GOODS_RECEIVED = 2;
    /**
     * Generated from protobuf enum <code>RETURN_STATUS_RESOLVED = 3;</code>
     */
    const RETURN_STATUS_RESOLVED = 3;
    /**
     * Generated from protobuf enum <code>RETURN_STATUS_REJECTED = 4;</code>
     */
    const RETURN_STATUS_REJECTED = 4;

    private static $valueToName = [
        self::RETURN_STATUS_UNSPECIFIED => 'RETURN_STATUS_UNSPECIFIED',
        self::RETURN_STATUS_OPEN => 'RETURN_STATUS_OPEN',
        self::RETURN_STATUS_GOODS_RECEIVED => 'RETURN_STATUS_GOODS_RECEIVED',
        self::RETURN_STATUS_RESOLVED => 'RETURN_STATUS_RESOLVED',
        self::RETURN_STATUS_REJECTED => 'RETURN_STATUS_REJECTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

