<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo/v1/geo.proto

namespace Geo\V1\GPBMetadata;

class Geo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Common\V1\GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x97\x0A\x0A\x10geo/v1/geo.proto\x12\x06geo.v1\"E\x0A\x15GeocodeAddressRequest\x12,\x0A\x07address\x18\x01 \x01(\x0B2\x12.common.v1.AddressR\x07address\"\xF6\x01\x0A\x16GeocodeAddressResponse\x12\x1A\x0A\x08geocoded\x18\x01 \x01(\x08R\x08geocoded\x12/\x0A\x08location\x18\x02 \x01(\x0B2\x13.common.v1.GeoPointR\x08location\x120\x0A\x07failure\x18\x03 \x01(\x0E2\x16.geo.v1.GeocodeFailureR\x07failure\x12%\x0A\x0Efailure_detail\x18\x04 \x01(\x09R\x0DfailureDetail\x126\x0A\x09precision\x18\x05 \x01(\x0E2\x18.geo.v1.GeocodePrecisionR\x09precision\"K\x0A\x17GeocodeAddressesRequest\x120\x0A\x09addresses\x18\x01 \x03(\x0B2\x12.common.v1.AddressR\x09addresses\"T\x0A\x18GeocodeAddressesResponse\x128\x0A\x07results\x18\x01 \x03(\x0B2\x1E.geo.v1.GeocodeAddressResponseR\x07results*\xEC\x01\x0A\x0EGeocodeFailure\x12\x1F\x0A\x1BGEOCODE_FAILURE_UNSPECIFIED\x10\x00\x12\x1D\x0A\x19GEOCODE_FAILURE_NOT_FOUND\x10\x01\x12\x1D\x0A\x19GEOCODE_FAILURE_AMBIGUOUS\x10\x02\x12(\x0A\$GEOCODE_FAILURE_PROVIDER_UNAVAILABLE\x10\x03\x12'\x0A#GEOCODE_FAILURE_OUT_OF_SERVICE_AREA\x10\x04\x12(\x0A\$GEOCODE_FAILURE_INSUFFICIENT_ADDRESS\x10\x05*\xAC\x01\x0A\x10GeocodePrecision\x12!\x0A\x1DGEOCODE_PRECISION_UNSPECIFIED\x10\x00\x12\x1D\x0A\x19GEOCODE_PRECISION_ROOFTOP\x10\x01\x12\x1C\x0A\x18GEOCODE_PRECISION_STREET\x10\x02\x12\x1C\x0A\x18GEOCODE_PRECISION_SUBURB\x10\x03\x12\x1A\x0A\x16GEOCODE_PRECISION_CITY\x10\x042\xBA\x01\x0A\x10GeocodingService\x12O\x0A\x0EGeocodeAddress\x12\x1D.geo.v1.GeocodeAddressRequest\x1A\x1E.geo.v1.GeocodeAddressResponse\x12U\x0A\x10GeocodeAddresses\x12\x1F.geo.v1.GeocodeAddressesRequest\x1A .geo.v1.GeocodeAddressesResponseB\xB4\x01\x0A\x1Ccom.kinetix.contracts.geo.v1B\x08GeoProtoP\x01Z?github.com/WildanFrananda/kinetix-contracts/gen/go/geo/v1;geov1\xA2\x02\x03KNX\xAA\x02\x18Kinetix.Contracts.Geo.V1\xCA\x02\x06Geo\\V1\xE2\x02\x12Geo\\V1\\GPBMetadata\xEA\x02\x07Geo::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

