<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.AllocateFlashSaleStockRequest</code>
 */
class AllocateFlashSaleStockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string flash_sale_id = 1 [json_name = "flashSaleId"];</code>
     */
    protected $flash_sale_id = '';
    /**
     * Generated from protobuf field <code>string product_id = 2 [json_name = "productId"];</code>
     */
    protected $product_id = '';
    /**
     * Generated from protobuf field <code>int32 quantity = 3 [json_name = "quantity"];</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>string order_number = 4 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $flash_sale_id
     *     @type string $product_id
     *     @type int $quantity
     *     @type string $order_number
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string flash_sale_id = 1 [json_name = "flashSaleId"];</code>
     * @return string
     */
    public function getFlashSaleId()
    {
        return $this->flash_sale_id;
    }

    /**
     * Generated from protobuf field <code>string flash_sale_id = 1 [json_name = "flashSaleId"];</code>
     * @param string $var
     * @return $this
     */
    public function setFlashSaleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->flash_sale_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_id = 2 [json_name = "productId"];</code>
     * @return string
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Generated from protobuf field <code>string product_id = 2 [json_name = "productId"];</code>
     * @param string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 3 [json_name = "quantity"];</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 3 [json_name = "quantity"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 4 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 4 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

}

