<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.CalculatePriceResponse</code>
 */
class CalculatePriceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.v1.Money subtotal = 1 [json_name = "subtotal"];</code>
     */
    protected $subtotal = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money total_discount = 2 [json_name = "totalDiscount"];</code>
     */
    protected $total_discount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money voucher_discount = 3 [json_name = "voucherDiscount"];</code>
     */
    protected $voucher_discount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money final_total = 4 [json_name = "finalTotal"];</code>
     */
    protected $final_total = null;
    /**
     * Generated from protobuf field <code>optional string applied_voucher = 5 [json_name = "appliedVoucher"];</code>
     */
    protected $applied_voucher = null;
    /**
     * Generated from protobuf field <code>repeated .pricing.v1.PriceItemResponse items = 6 [json_name = "items"];</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 7 [json_name = "baseShippingFee"];</code>
     */
    protected $base_shipping_fee = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_discount = 8 [json_name = "shippingDiscount"];</code>
     */
    protected $shipping_discount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money final_shipping_fee = 9 [json_name = "finalShippingFee"];</code>
     */
    protected $final_shipping_fee = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money payment_discount = 10 [json_name = "paymentDiscount"];</code>
     */
    protected $payment_discount = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Common\V1\Money $subtotal
     *     @type \Common\V1\Money $total_discount
     *     @type \Common\V1\Money $voucher_discount
     *     @type \Common\V1\Money $final_total
     *     @type string $applied_voucher
     *     @type array<\Pricing\V1\PriceItemResponse>|\Google\Protobuf\Internal\RepeatedField $items
     *     @type \Common\V1\Money $base_shipping_fee
     *     @type \Common\V1\Money $shipping_discount
     *     @type \Common\V1\Money $final_shipping_fee
     *     @type \Common\V1\Money $payment_discount
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money subtotal = 1 [json_name = "subtotal"];</code>
     * @return \Common\V1\Money|null
     */
    public function getSubtotal()
    {
        return $this->subtotal;
    }

    public function hasSubtotal()
    {
        return isset($this->subtotal);
    }

    public function clearSubtotal()
    {
        unset($this->subtotal);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money subtotal = 1 [json_name = "subtotal"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setSubtotal($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->subtotal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_discount = 2 [json_name = "totalDiscount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getTotalDiscount()
    {
        return $this->total_discount;
    }

    public function hasTotalDiscount()
    {
        return isset($this->total_discount);
    }

    public function clearTotalDiscount()
    {
        unset($this->total_discount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_discount = 2 [json_name = "totalDiscount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setTotalDiscount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->total_discount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money voucher_discount = 3 [json_name = "voucherDiscount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getVoucherDiscount()
    {
        return $this->voucher_discount;
    }

    public function hasVoucherDiscount()
    {
        return isset($this->voucher_discount);
    }

    public function clearVoucherDiscount()
    {
        unset($this->voucher_discount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money voucher_discount = 3 [json_name = "voucherDiscount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setVoucherDiscount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->voucher_discount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_total = 4 [json_name = "finalTotal"];</code>
     * @return \Common\V1\Money|null
     */
    public function getFinalTotal()
    {
        return $this->final_total;
    }

    public function hasFinalTotal()
    {
        return isset($this->final_total);
    }

    public function clearFinalTotal()
    {
        unset($this->final_total);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_total = 4 [json_name = "finalTotal"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setFinalTotal($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->final_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string applied_voucher = 5 [json_name = "appliedVoucher"];</code>
     * @return string
     */
    public function getAppliedVoucher()
    {
        return isset($this->applied_voucher) ? $this->applied_voucher : '';
    }

    public function hasAppliedVoucher()
    {
        return isset($this->applied_voucher);
    }

    public function clearAppliedVoucher()
    {
        unset($this->applied_voucher);
    }

    /**
     * Generated from protobuf field <code>optional string applied_voucher = 5 [json_name = "appliedVoucher"];</code>
     * @param string $var
     * @return $this
     */
    public function setAppliedVoucher($var)
    {
        GPBUtil::checkString($var, True);
        $this->applied_voucher = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.PriceItemResponse items = 6 [json_name = "items"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.PriceItemResponse items = 6 [json_name = "items"];</code>
     * @param array<\Pricing\V1\PriceItemResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pricing\V1\PriceItemResponse::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 7 [json_name = "baseShippingFee"];</code>
     * @return \Common\V1\Money|null
     */
    public function getBaseShippingFee()
    {
        return $this->base_shipping_fee;
    }

    public function hasBaseShippingFee()
    {
        return isset($this->base_shipping_fee);
    }

    public function clearBaseShippingFee()
    {
        unset($this->base_shipping_fee);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 7 [json_name = "baseShippingFee"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setBaseShippingFee($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->base_shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_discount = 8 [json_name = "shippingDiscount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getShippingDiscount()
    {
        return $this->shipping_discount;
    }

    public function hasShippingDiscount()
    {
        return isset($this->shipping_discount);
    }

    public function clearShippingDiscount()
    {
        unset($this->shipping_discount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_discount = 8 [json_name = "shippingDiscount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setShippingDiscount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->shipping_discount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_shipping_fee = 9 [json_name = "finalShippingFee"];</code>
     * @return \Common\V1\Money|null
     */
    public function getFinalShippingFee()
    {
        return $this->final_shipping_fee;
    }

    public function hasFinalShippingFee()
    {
        return isset($this->final_shipping_fee);
    }

    public function clearFinalShippingFee()
    {
        unset($this->final_shipping_fee);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_shipping_fee = 9 [json_name = "finalShippingFee"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setFinalShippingFee($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->final_shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money payment_discount = 10 [json_name = "paymentDiscount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getPaymentDiscount()
    {
        return $this->payment_discount;
    }

    public function hasPaymentDiscount()
    {
        return isset($this->payment_discount);
    }

    public function clearPaymentDiscount()
    {
        unset($this->payment_discount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money payment_discount = 10 [json_name = "paymentDiscount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setPaymentDiscount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->payment_discount = $var;

        return $this;
    }

}

