<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.CalculatePriceRequest</code>
 */
class CalculatePriceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pricing.v1.PriceItemRequest items = 1 [json_name = "items"];</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>optional string voucher_code = 2 [json_name = "voucherCode"];</code>
     */
    protected $voucher_code = null;
    /**
     * Generated from protobuf field <code>optional .common.v1.Money base_shipping_fee = 3 [json_name = "baseShippingFee", deprecated = true];</code>
     * @deprecated
     */
    protected $base_shipping_fee = null;
    /**
     * Generated from protobuf field <code>optional string payment_method = 4 [json_name = "paymentMethod"];</code>
     */
    protected $payment_method = null;
    /**
     * Generated from protobuf field <code>optional .pricing.v1.ShippingQuoteRequest shipping = 5 [json_name = "shipping"];</code>
     */
    protected $shipping = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Pricing\V1\PriceItemRequest>|\Google\Protobuf\Internal\RepeatedField $items
     *     @type string $voucher_code
     *     @type \Common\V1\Money $base_shipping_fee
     *     @type string $payment_method
     *     @type \Pricing\V1\ShippingQuoteRequest $shipping
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.PriceItemRequest items = 1 [json_name = "items"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.PriceItemRequest items = 1 [json_name = "items"];</code>
     * @param array<\Pricing\V1\PriceItemRequest>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pricing\V1\PriceItemRequest::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string voucher_code = 2 [json_name = "voucherCode"];</code>
     * @return string
     */
    public function getVoucherCode()
    {
        return isset($this->voucher_code) ? $this->voucher_code : '';
    }

    public function hasVoucherCode()
    {
        return isset($this->voucher_code);
    }

    public function clearVoucherCode()
    {
        unset($this->voucher_code);
    }

    /**
     * Generated from protobuf field <code>optional string voucher_code = 2 [json_name = "voucherCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setVoucherCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->voucher_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .common.v1.Money base_shipping_fee = 3 [json_name = "baseShippingFee", deprecated = true];</code>
     * @return \Common\V1\Money|null
     * @deprecated
     */
    public function getBaseShippingFee()
    {
        if (isset($this->base_shipping_fee)) {
            @trigger_error('base_shipping_fee is deprecated.', E_USER_DEPRECATED);
        }
        return $this->base_shipping_fee;
    }

    public function hasBaseShippingFee()
    {
        if (isset($this->base_shipping_fee)) {
            @trigger_error('base_shipping_fee is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->base_shipping_fee);
    }

    public function clearBaseShippingFee()
    {
        @trigger_error('base_shipping_fee is deprecated.', E_USER_DEPRECATED);
        unset($this->base_shipping_fee);
    }

    /**
     * Generated from protobuf field <code>optional .common.v1.Money base_shipping_fee = 3 [json_name = "baseShippingFee", deprecated = true];</code>
     * @param \Common\V1\Money $var
     * @return $this
     * @deprecated
     */
    public function setBaseShippingFee($var)
    {
        @trigger_error('base_shipping_fee is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->base_shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string payment_method = 4 [json_name = "paymentMethod"];</code>
     * @return string
     */
    public function getPaymentMethod()
    {
        return isset($this->payment_method) ? $this->payment_method : '';
    }

    public function hasPaymentMethod()
    {
        return isset($this->payment_method);
    }

    public function clearPaymentMethod()
    {
        unset($this->payment_method);
    }

    /**
     * Generated from protobuf field <code>optional string payment_method = 4 [json_name = "paymentMethod"];</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .pricing.v1.ShippingQuoteRequest shipping = 5 [json_name = "shipping"];</code>
     * @return \Pricing\V1\ShippingQuoteRequest|null
     */
    public function getShipping()
    {
        return $this->shipping;
    }

    public function hasShipping()
    {
        return isset($this->shipping);
    }

    public function clearShipping()
    {
        unset($this->shipping);
    }

    /**
     * Generated from protobuf field <code>optional .pricing.v1.ShippingQuoteRequest shipping = 5 [json_name = "shipping"];</code>
     * @param \Pricing\V1\ShippingQuoteRequest $var
     * @return $this
     */
    public function setShipping($var)
    {
        GPBUtil::checkMessage($var, \Pricing\V1\ShippingQuoteRequest::class);
        $this->shipping = $var;

        return $this;
    }

}

