<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>pricing.v1.DiscountScope</code>
 */
class DiscountScope
{
    /**
     * Generated from protobuf enum <code>DISCOUNT_SCOPE_UNSPECIFIED = 0;</code>
     */
    const DISCOUNT_SCOPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DISCOUNT_SCOPE_PER_UNIT = 1;</code>
     */
    const DISCOUNT_SCOPE_PER_UNIT = 1;
    /**
     * Generated from protobuf enum <code>DISCOUNT_SCOPE_PER_CART = 2;</code>
     */
    const DISCOUNT_SCOPE_PER_CART = 2;

    private static $valueToName = [
        self::DISCOUNT_SCOPE_UNSPECIFIED => 'DISCOUNT_SCOPE_UNSPECIFIED',
        self::DISCOUNT_SCOPE_PER_UNIT => 'DISCOUNT_SCOPE_PER_UNIT',
        self::DISCOUNT_SCOPE_PER_CART => 'DISCOUNT_SCOPE_PER_CART',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

