<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>pricing.v1.DiscountType</code>
 */
class DiscountType
{
    /**
     * Generated from protobuf enum <code>DISCOUNT_TYPE_UNSPECIFIED = 0;</code>
     */
    const DISCOUNT_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DISCOUNT_TYPE_PERCENTAGE = 1;</code>
     */
    const DISCOUNT_TYPE_PERCENTAGE = 1;
    /**
     * Generated from protobuf enum <code>DISCOUNT_TYPE_FIXED = 2;</code>
     */
    const DISCOUNT_TYPE_FIXED = 2;

    private static $valueToName = [
        self::DISCOUNT_TYPE_UNSPECIFIED => 'DISCOUNT_TYPE_UNSPECIFIED',
        self::DISCOUNT_TYPE_PERCENTAGE => 'DISCOUNT_TYPE_PERCENTAGE',
        self::DISCOUNT_TYPE_FIXED => 'DISCOUNT_TYPE_FIXED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

