<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.PriceItemRequest</code>
 */
class PriceItemRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string product_id = 1 [json_name = "productId"];</code>
     */
    protected $product_id = '';
    /**
     * Generated from protobuf field <code>optional string category_id = 2 [json_name = "categoryId"];</code>
     */
    protected $category_id = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money base_price = 3 [json_name = "basePrice"];</code>
     */
    protected $base_price = null;
    /**
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     */
    protected $quantity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $product_id
     *     @type string $category_id
     *     @type \Common\V1\Money $base_price
     *     @type int $quantity
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string product_id = 1 [json_name = "productId"];</code>
     * @return string
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Generated from protobuf field <code>string product_id = 1 [json_name = "productId"];</code>
     * @param string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string category_id = 2 [json_name = "categoryId"];</code>
     * @return string
     */
    public function getCategoryId()
    {
        return isset($this->category_id) ? $this->category_id : '';
    }

    public function hasCategoryId()
    {
        return isset($this->category_id);
    }

    public function clearCategoryId()
    {
        unset($this->category_id);
    }

    /**
     * Generated from protobuf field <code>optional string category_id = 2 [json_name = "categoryId"];</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_price = 3 [json_name = "basePrice"];</code>
     * @return \Common\V1\Money|null
     */
    public function getBasePrice()
    {
        return $this->base_price;
    }

    public function hasBasePrice()
    {
        return isset($this->base_price);
    }

    public function clearBasePrice()
    {
        unset($this->base_price);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_price = 3 [json_name = "basePrice"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setBasePrice($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->base_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

}

