<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.PriceItemResponse</code>
 */
class PriceItemResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string product_id = 1 [json_name = "productId"];</code>
     */
    protected $product_id = '';
    /**
     * Generated from protobuf field <code>.common.v1.Money base_price = 2 [json_name = "basePrice"];</code>
     */
    protected $base_price = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money final_unit_price = 3 [json_name = "finalUnitPrice"];</code>
     */
    protected $final_unit_price = null;
    /**
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>.common.v1.Money line_total = 5 [json_name = "lineTotal"];</code>
     */
    protected $line_total = null;
    /**
     * Generated from protobuf field <code>optional string applied_flash_sale = 6 [json_name = "appliedFlashSale"];</code>
     */
    protected $applied_flash_sale = null;
    /**
     * Generated from protobuf field <code>optional string applied_discount = 7 [json_name = "appliedDiscount"];</code>
     */
    protected $applied_discount = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $product_id
     *     @type \Common\V1\Money $base_price
     *     @type \Common\V1\Money $final_unit_price
     *     @type int $quantity
     *     @type \Common\V1\Money $line_total
     *     @type string $applied_flash_sale
     *     @type string $applied_discount
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string product_id = 1 [json_name = "productId"];</code>
     * @return string
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Generated from protobuf field <code>string product_id = 1 [json_name = "productId"];</code>
     * @param string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_price = 2 [json_name = "basePrice"];</code>
     * @return \Common\V1\Money|null
     */
    public function getBasePrice()
    {
        return $this->base_price;
    }

    public function hasBasePrice()
    {
        return isset($this->base_price);
    }

    public function clearBasePrice()
    {
        unset($this->base_price);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_price = 2 [json_name = "basePrice"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setBasePrice($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->base_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_unit_price = 3 [json_name = "finalUnitPrice"];</code>
     * @return \Common\V1\Money|null
     */
    public function getFinalUnitPrice()
    {
        return $this->final_unit_price;
    }

    public function hasFinalUnitPrice()
    {
        return isset($this->final_unit_price);
    }

    public function clearFinalUnitPrice()
    {
        unset($this->final_unit_price);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money final_unit_price = 3 [json_name = "finalUnitPrice"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setFinalUnitPrice($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->final_unit_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money line_total = 5 [json_name = "lineTotal"];</code>
     * @return \Common\V1\Money|null
     */
    public function getLineTotal()
    {
        return $this->line_total;
    }

    public function hasLineTotal()
    {
        return isset($this->line_total);
    }

    public function clearLineTotal()
    {
        unset($this->line_total);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money line_total = 5 [json_name = "lineTotal"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setLineTotal($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->line_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string applied_flash_sale = 6 [json_name = "appliedFlashSale"];</code>
     * @return string
     */
    public function getAppliedFlashSale()
    {
        return isset($this->applied_flash_sale) ? $this->applied_flash_sale : '';
    }

    public function hasAppliedFlashSale()
    {
        return isset($this->applied_flash_sale);
    }

    public function clearAppliedFlashSale()
    {
        unset($this->applied_flash_sale);
    }

    /**
     * Generated from protobuf field <code>optional string applied_flash_sale = 6 [json_name = "appliedFlashSale"];</code>
     * @param string $var
     * @return $this
     */
    public function setAppliedFlashSale($var)
    {
        GPBUtil::checkString($var, True);
        $this->applied_flash_sale = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string applied_discount = 7 [json_name = "appliedDiscount"];</code>
     * @return string
     */
    public function getAppliedDiscount()
    {
        return isset($this->applied_discount) ? $this->applied_discount : '';
    }

    public function hasAppliedDiscount()
    {
        return isset($this->applied_discount);
    }

    public function clearAppliedDiscount()
    {
        unset($this->applied_discount);
    }

    /**
     * Generated from protobuf field <code>optional string applied_discount = 7 [json_name = "appliedDiscount"];</code>
     * @param string $var
     * @return $this
     */
    public function setAppliedDiscount($var)
    {
        GPBUtil::checkString($var, True);
        $this->applied_discount = $var;

        return $this;
    }

}

