<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.QuotedShipping</code>
 */
class QuotedShipping extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     */
    protected $service_tier = '';
    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 2 [json_name = "baseShippingFee"];</code>
     */
    protected $base_shipping_fee = null;
    /**
     * Generated from protobuf field <code>bool priced = 3 [json_name = "priced"];</code>
     */
    protected $priced = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service_tier
     *     @type \Common\V1\Money $base_shipping_fee
     *     @type bool $priced
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     * @return string
     */
    public function getServiceTier()
    {
        return $this->service_tier;
    }

    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceTier($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_tier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 2 [json_name = "baseShippingFee"];</code>
     * @return \Common\V1\Money|null
     */
    public function getBaseShippingFee()
    {
        return $this->base_shipping_fee;
    }

    public function hasBaseShippingFee()
    {
        return isset($this->base_shipping_fee);
    }

    public function clearBaseShippingFee()
    {
        unset($this->base_shipping_fee);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money base_shipping_fee = 2 [json_name = "baseShippingFee"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setBaseShippingFee($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->base_shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool priced = 3 [json_name = "priced"];</code>
     * @return bool
     */
    public function getPriced()
    {
        return $this->priced;
    }

    /**
     * Generated from protobuf field <code>bool priced = 3 [json_name = "priced"];</code>
     * @param bool $var
     * @return $this
     */
    public function setPriced($var)
    {
        GPBUtil::checkBool($var);
        $this->priced = $var;

        return $this;
    }

}

