<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.QuoteShippingRequest</code>
 */
class QuoteShippingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pricing.v1.ShippingQuoteRequest journeys = 1 [json_name = "journeys"];</code>
     */
    private $journeys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Pricing\V1\ShippingQuoteRequest>|\Google\Protobuf\Internal\RepeatedField $journeys
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.ShippingQuoteRequest journeys = 1 [json_name = "journeys"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJourneys()
    {
        return $this->journeys;
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.ShippingQuoteRequest journeys = 1 [json_name = "journeys"];</code>
     * @param array<\Pricing\V1\ShippingQuoteRequest>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJourneys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pricing\V1\ShippingQuoteRequest::class);
        $this->journeys = $arr;

        return $this;
    }

}

