<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.QuoteShippingResponse</code>
 */
class QuoteShippingResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pricing.v1.QuotedShipping quotes = 1 [json_name = "quotes"];</code>
     */
    private $quotes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Pricing\V1\QuotedShipping>|\Google\Protobuf\Internal\RepeatedField $quotes
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.QuotedShipping quotes = 1 [json_name = "quotes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQuotes()
    {
        return $this->quotes;
    }

    /**
     * Generated from protobuf field <code>repeated .pricing.v1.QuotedShipping quotes = 1 [json_name = "quotes"];</code>
     * @param array<\Pricing\V1\QuotedShipping>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQuotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pricing\V1\QuotedShipping::class);
        $this->quotes = $arr;

        return $this;
    }

}

