<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.ShippingQuoteRequest</code>
 */
class ShippingQuoteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     */
    protected $service_tier = '';
    /**
     * Generated from protobuf field <code>double distance_km = 2 [json_name = "distanceKm"];</code>
     */
    protected $distance_km = 0.0;
    /**
     * Generated from protobuf field <code>int64 total_weight_grams = 3 [json_name = "totalWeightGrams"];</code>
     */
    protected $total_weight_grams = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service_tier
     *     @type float $distance_km
     *     @type int|string $total_weight_grams
     * }
     */
    public function __construct($data = NULL) {
        \Pricing\V1\GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     * @return string
     */
    public function getServiceTier()
    {
        return $this->service_tier;
    }

    /**
     * Generated from protobuf field <code>string service_tier = 1 [json_name = "serviceTier"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceTier($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_tier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double distance_km = 2 [json_name = "distanceKm"];</code>
     * @return float
     */
    public function getDistanceKm()
    {
        return $this->distance_km;
    }

    /**
     * Generated from protobuf field <code>double distance_km = 2 [json_name = "distanceKm"];</code>
     * @param float $var
     * @return $this
     */
    public function setDistanceKm($var)
    {
        GPBUtil::checkDouble($var);
        $this->distance_km = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_weight_grams = 3 [json_name = "totalWeightGrams"];</code>
     * @return int|string
     */
    public function getTotalWeightGrams()
    {
        return $this->total_weight_grams;
    }

    /**
     * Generated from protobuf field <code>int64 total_weight_grams = 3 [json_name = "totalWeightGrams"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWeightGrams($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_weight_grams = $var;

        return $this;
    }

}

