<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/v1/payment.proto

namespace Payment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>payment.v1.CreateEscrowHoldRequest</code>
 */
class CreateEscrowHoldRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>string customer_principal_id = 2 [json_name = "customerPrincipalId"];</code>
     */
    protected $customer_principal_id = '';
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string driver_principal_id = 4 [json_name = "driverPrincipalId"];</code>
     */
    protected $driver_principal_id = '';
    /**
     * Generated from protobuf field <code>.common.v1.Money total_order_amount = 5 [json_name = "totalOrderAmount"];</code>
     */
    protected $total_order_amount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money merchant_amount = 6 [json_name = "merchantAmount"];</code>
     */
    protected $merchant_amount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee_amount = 7 [json_name = "shippingFeeAmount"];</code>
     */
    protected $shipping_fee_amount = null;
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $order_number
     *     @type string $customer_principal_id
     *     @type string $merchant_principal_id
     *     @type string $driver_principal_id
     *     @type \Common\V1\Money $total_order_amount
     *     @type \Common\V1\Money $merchant_amount
     *     @type \Common\V1\Money $shipping_fee_amount
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \Payment\V1\GPBMetadata\Payment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_principal_id = 2 [json_name = "customerPrincipalId"];</code>
     * @return string
     */
    public function getCustomerPrincipalId()
    {
        return $this->customer_principal_id;
    }

    /**
     * Generated from protobuf field <code>string customer_principal_id = 2 [json_name = "customerPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 4 [json_name = "driverPrincipalId"];</code>
     * @return string
     */
    public function getDriverPrincipalId()
    {
        return $this->driver_principal_id;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 4 [json_name = "driverPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDriverPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_order_amount = 5 [json_name = "totalOrderAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getTotalOrderAmount()
    {
        return $this->total_order_amount;
    }

    public function hasTotalOrderAmount()
    {
        return isset($this->total_order_amount);
    }

    public function clearTotalOrderAmount()
    {
        unset($this->total_order_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_order_amount = 5 [json_name = "totalOrderAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setTotalOrderAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->total_order_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money merchant_amount = 6 [json_name = "merchantAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getMerchantAmount()
    {
        return $this->merchant_amount;
    }

    public function hasMerchantAmount()
    {
        return isset($this->merchant_amount);
    }

    public function clearMerchantAmount()
    {
        unset($this->merchant_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money merchant_amount = 6 [json_name = "merchantAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setMerchantAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->merchant_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee_amount = 7 [json_name = "shippingFeeAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getShippingFeeAmount()
    {
        return $this->shipping_fee_amount;
    }

    public function hasShippingFeeAmount()
    {
        return isset($this->shipping_fee_amount);
    }

    public function clearShippingFeeAmount()
    {
        unset($this->shipping_fee_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee_amount = 7 [json_name = "shippingFeeAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setShippingFeeAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->shipping_fee_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

}

