<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/v1/payment.proto

namespace Payment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>payment.v1.EscrowHoldResponse</code>
 */
class EscrowHoldResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string escrow_id = 2 [json_name = "escrowId"];</code>
     */
    protected $escrow_id = '';
    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>string customer_principal_id = 4 [json_name = "customerPrincipalId"];</code>
     */
    protected $customer_principal_id = '';
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 5 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string driver_principal_id = 6 [json_name = "driverPrincipalId"];</code>
     */
    protected $driver_principal_id = '';
    /**
     * Generated from protobuf field <code>.common.v1.Money total_order_amount = 7 [json_name = "totalOrderAmount"];</code>
     */
    protected $total_order_amount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money merchant_amount = 8 [json_name = "merchantAmount"];</code>
     */
    protected $merchant_amount = null;
    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee_amount = 9 [json_name = "shippingFeeAmount"];</code>
     */
    protected $shipping_fee_amount = null;
    /**
     * Generated from protobuf field <code>.payment.v1.EscrowStatus status = 10 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp auto_release_at = 11 [json_name = "autoReleaseAt"];</code>
     */
    protected $auto_release_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp released_at = 13 [json_name = "releasedAt"];</code>
     */
    protected $released_at = null;
    /**
     * Generated from protobuf field <code>bool already_applied = 14 [json_name = "alreadyApplied"];</code>
     */
    protected $already_applied = false;
    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 15 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $escrow_id
     *     @type string $order_number
     *     @type string $customer_principal_id
     *     @type string $merchant_principal_id
     *     @type string $driver_principal_id
     *     @type \Common\V1\Money $total_order_amount
     *     @type \Common\V1\Money $merchant_amount
     *     @type \Common\V1\Money $shipping_fee_amount
     *     @type int $status
     *     @type \Google\Protobuf\Timestamp $auto_release_at
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $released_at
     *     @type bool $already_applied
     *     @type \Common\V1\ErrorDetail $error
     * }
     */
    public function __construct($data = NULL) {
        \Payment\V1\GPBMetadata\Payment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string escrow_id = 2 [json_name = "escrowId"];</code>
     * @return string
     */
    public function getEscrowId()
    {
        return $this->escrow_id;
    }

    /**
     * Generated from protobuf field <code>string escrow_id = 2 [json_name = "escrowId"];</code>
     * @param string $var
     * @return $this
     */
    public function setEscrowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->escrow_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 3 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_principal_id = 4 [json_name = "customerPrincipalId"];</code>
     * @return string
     */
    public function getCustomerPrincipalId()
    {
        return $this->customer_principal_id;
    }

    /**
     * Generated from protobuf field <code>string customer_principal_id = 4 [json_name = "customerPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 5 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 5 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 6 [json_name = "driverPrincipalId"];</code>
     * @return string
     */
    public function getDriverPrincipalId()
    {
        return $this->driver_principal_id;
    }

    /**
     * Generated from protobuf field <code>string driver_principal_id = 6 [json_name = "driverPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDriverPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_order_amount = 7 [json_name = "totalOrderAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getTotalOrderAmount()
    {
        return $this->total_order_amount;
    }

    public function hasTotalOrderAmount()
    {
        return isset($this->total_order_amount);
    }

    public function clearTotalOrderAmount()
    {
        unset($this->total_order_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money total_order_amount = 7 [json_name = "totalOrderAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setTotalOrderAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->total_order_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money merchant_amount = 8 [json_name = "merchantAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getMerchantAmount()
    {
        return $this->merchant_amount;
    }

    public function hasMerchantAmount()
    {
        return isset($this->merchant_amount);
    }

    public function clearMerchantAmount()
    {
        unset($this->merchant_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money merchant_amount = 8 [json_name = "merchantAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setMerchantAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->merchant_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee_amount = 9 [json_name = "shippingFeeAmount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getShippingFeeAmount()
    {
        return $this->shipping_fee_amount;
    }

    public function hasShippingFeeAmount()
    {
        return isset($this->shipping_fee_amount);
    }

    public function clearShippingFeeAmount()
    {
        unset($this->shipping_fee_amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money shipping_fee_amount = 9 [json_name = "shippingFeeAmount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setShippingFeeAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->shipping_fee_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.payment.v1.EscrowStatus status = 10 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.payment.v1.EscrowStatus status = 10 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Payment\V1\EscrowStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp auto_release_at = 11 [json_name = "autoReleaseAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getAutoReleaseAt()
    {
        return $this->auto_release_at;
    }

    public function hasAutoReleaseAt()
    {
        return isset($this->auto_release_at);
    }

    public function clearAutoReleaseAt()
    {
        unset($this->auto_release_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp auto_release_at = 11 [json_name = "autoReleaseAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setAutoReleaseAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->auto_release_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp released_at = 13 [json_name = "releasedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getReleasedAt()
    {
        return $this->released_at;
    }

    public function hasReleasedAt()
    {
        return isset($this->released_at);
    }

    public function clearReleasedAt()
    {
        unset($this->released_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp released_at = 13 [json_name = "releasedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setReleasedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->released_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool already_applied = 14 [json_name = "alreadyApplied"];</code>
     * @return bool
     */
    public function getAlreadyApplied()
    {
        return $this->already_applied;
    }

    /**
     * Generated from protobuf field <code>bool already_applied = 14 [json_name = "alreadyApplied"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyApplied($var)
    {
        GPBUtil::checkBool($var);
        $this->already_applied = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 15 [json_name = "error"];</code>
     * @return \Common\V1\ErrorDetail|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 15 [json_name = "error"];</code>
     * @param \Common\V1\ErrorDetail $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\ErrorDetail::class);
        $this->error = $var;

        return $this;
    }

}

