<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/v1/payment.proto

namespace Payment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>payment.v1.RefundGoodsRequest</code>
 */
class RefundGoodsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     */
    protected $order_number = '';
    /**
     * Generated from protobuf field <code>.common.v1.Money amount = 2 [json_name = "amount"];</code>
     */
    protected $amount = null;
    /**
     * Generated from protobuf field <code>string reason = 3 [json_name = "reason"];</code>
     */
    protected $reason = '';
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 4 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $order_number
     *     @type \Common\V1\Money $amount
     *     @type string $reason
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \Payment\V1\GPBMetadata\Payment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 1 [json_name = "orderNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money amount = 2 [json_name = "amount"];</code>
     * @return \Common\V1\Money|null
     */
    public function getAmount()
    {
        return $this->amount;
    }

    public function hasAmount()
    {
        return isset($this->amount);
    }

    public function clearAmount()
    {
        unset($this->amount);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Money amount = 2 [json_name = "amount"];</code>
     * @param \Common\V1\Money $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Money::class);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 3 [json_name = "reason"];</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 3 [json_name = "reason"];</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 4 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 4 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

}

