<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulfillment/v1/task.proto

namespace Fulfillment\V1\GPBMetadata;

class Task
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Common\V1\GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAF\x0A\x0A\x19fulfillment/v1/task.proto\x12\x0Efulfillment.v1\"C\x0A\x13FulfillmentTaskLine\x12\x10\x0A\x03sku\x18\x01 \x01(\x09R\x03sku\x12\x1A\x0A\x08quantity\x18\x02 \x01(\x05R\x08quantity\"\xF4\x01\x0A\x1CCreateFulfillmentTaskRequest\x122\x0A\x15merchant_principal_id\x18\x01 \x01(\x09R\x13merchantPrincipalId\x12!\x0A\x0Corder_number\x18\x02 \x01(\x09R\x0BorderNumber\x129\x0A\x05lines\x18\x03 \x03(\x0B2#.fulfillment.v1.FulfillmentTaskLineR\x05lines\x12B\x0A\x0Fidempotency_key\x18\x04 \x01(\x0B2\x19.common.v1.IdempotencyKeyR\x0EidempotencyKey\"\xA9\x01\x0A\x1DCreateFulfillmentTaskResponse\x12\x18\x0A\x07success\x18\x01 \x01(\x08R\x07success\x12\x17\x0A\x07task_id\x18\x02 \x01(\x09R\x06taskId\x12'\x0A\x0Falready_created\x18\x03 \x01(\x08R\x0EalreadyCreated\x12,\x0A\x05error\x18\x04 \x01(\x0B2\x16.common.v1.ErrorDetailR\x05error\"\x83\x01\x0A\x1CCancelFulfillmentTaskRequest\x122\x0A\x15merchant_principal_id\x18\x01 \x01(\x09R\x13merchantPrincipalId\x12\x17\x0A\x07task_id\x18\x02 \x01(\x09R\x06taskId\x12\x16\x0A\x06reason\x18\x03 \x01(\x09R\x06reason\"\x94\x01\x0A\x1DCancelFulfillmentTaskResponse\x12\x18\x0A\x07success\x18\x01 \x01(\x08R\x07success\x12+\x0A\x11already_cancelled\x18\x02 \x01(\x08R\x10alreadyCancelled\x12,\x0A\x05error\x18\x03 \x01(\x0B2\x16.common.v1.ErrorDetailR\x05error2\x84\x02\x0A\x16FulfillmentTaskService\x12t\x0A\x15CreateFulfillmentTask\x12,.fulfillment.v1.CreateFulfillmentTaskRequest\x1A-.fulfillment.v1.CreateFulfillmentTaskResponse\x12t\x0A\x15CancelFulfillmentTask\x12,.fulfillment.v1.CancelFulfillmentTaskRequest\x1A-.fulfillment.v1.CancelFulfillmentTaskResponseB\xED\x01\x0A\$com.kinetix.contracts.fulfillment.v1B\x09TaskProtoP\x01ZOgithub.com/WildanFrananda/kinetix-contracts/gen/go/fulfillment/v1;fulfillmentv1\xA2\x02\x03KNX\xAA\x02 Kinetix.Contracts.Fulfillment.V1\xCA\x02\x0EFulfillment\\V1\xE2\x02\x1AFulfillment\\V1\\GPBMetadata\xEA\x02\x0FFulfillment::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

