<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1/search.proto

namespace Search\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>search.v1.FacetValue</code>
 */
class FacetValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string value = 1 [json_name = "value"];</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>int64 count = 2 [json_name = "count"];</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *     @type int|string $count
     * }
     */
    public function __construct($data = NULL) {
        \Search\V1\GPBMetadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string value = 1 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 1 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count = 2 [json_name = "count"];</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int64 count = 2 [json_name = "count"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

}

