<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1/search.proto

namespace Search\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>search.v1.IndexFreshness</code>
 */
class IndexFreshness extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp indexed_through = 1 [json_name = "indexedThrough"];</code>
     */
    protected $indexed_through = null;
    /**
     * Generated from protobuf field <code>int64 age_seconds = 2 [json_name = "ageSeconds"];</code>
     */
    protected $age_seconds = 0;
    /**
     * Generated from protobuf field <code>bool stale = 3 [json_name = "stale"];</code>
     */
    protected $stale = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $indexed_through
     *     @type int|string $age_seconds
     *     @type bool $stale
     * }
     */
    public function __construct($data = NULL) {
        \Search\V1\GPBMetadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp indexed_through = 1 [json_name = "indexedThrough"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getIndexedThrough()
    {
        return $this->indexed_through;
    }

    public function hasIndexedThrough()
    {
        return isset($this->indexed_through);
    }

    public function clearIndexedThrough()
    {
        unset($this->indexed_through);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp indexed_through = 1 [json_name = "indexedThrough"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setIndexedThrough($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->indexed_through = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 age_seconds = 2 [json_name = "ageSeconds"];</code>
     * @return int|string
     */
    public function getAgeSeconds()
    {
        return $this->age_seconds;
    }

    /**
     * Generated from protobuf field <code>int64 age_seconds = 2 [json_name = "ageSeconds"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAgeSeconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->age_seconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool stale = 3 [json_name = "stale"];</code>
     * @return bool
     */
    public function getStale()
    {
        return $this->stale;
    }

    /**
     * Generated from protobuf field <code>bool stale = 3 [json_name = "stale"];</code>
     * @param bool $var
     * @return $this
     */
    public function setStale($var)
    {
        GPBUtil::checkBool($var);
        $this->stale = $var;

        return $this;
    }

}

