<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1/search.proto

namespace Search\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>search.v1.SearchProductsResponse</code>
 */
class SearchProductsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .search.v1.ProductHit hits = 1 [json_name = "hits"];</code>
     */
    private $hits;
    /**
     * Generated from protobuf field <code>int64 total = 2 [json_name = "total"];</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>repeated .search.v1.Facet facets = 3 [json_name = "facets"];</code>
     */
    private $facets;
    /**
     * Generated from protobuf field <code>.search.v1.IndexFreshness freshness = 4 [json_name = "freshness"];</code>
     */
    protected $freshness = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Search\V1\ProductHit>|\Google\Protobuf\Internal\RepeatedField $hits
     *     @type int|string $total
     *     @type array<\Search\V1\Facet>|\Google\Protobuf\Internal\RepeatedField $facets
     *     @type \Search\V1\IndexFreshness $freshness
     * }
     */
    public function __construct($data = NULL) {
        \Search\V1\GPBMetadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .search.v1.ProductHit hits = 1 [json_name = "hits"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHits()
    {
        return $this->hits;
    }

    /**
     * Generated from protobuf field <code>repeated .search.v1.ProductHit hits = 1 [json_name = "hits"];</code>
     * @param array<\Search\V1\ProductHit>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHits($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Search\V1\ProductHit::class);
        $this->hits = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total = 2 [json_name = "total"];</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 2 [json_name = "total"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .search.v1.Facet facets = 3 [json_name = "facets"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFacets()
    {
        return $this->facets;
    }

    /**
     * Generated from protobuf field <code>repeated .search.v1.Facet facets = 3 [json_name = "facets"];</code>
     * @param array<\Search\V1\Facet>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFacets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Search\V1\Facet::class);
        $this->facets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.search.v1.IndexFreshness freshness = 4 [json_name = "freshness"];</code>
     * @return \Search\V1\IndexFreshness|null
     */
    public function getFreshness()
    {
        return $this->freshness;
    }

    public function hasFreshness()
    {
        return isset($this->freshness);
    }

    public function clearFreshness()
    {
        unset($this->freshness);
    }

    /**
     * Generated from protobuf field <code>.search.v1.IndexFreshness freshness = 4 [json_name = "freshness"];</code>
     * @param \Search\V1\IndexFreshness $var
     * @return $this
     */
    public function setFreshness($var)
    {
        GPBUtil::checkMessage($var, \Search\V1\IndexFreshness::class);
        $this->freshness = $var;

        return $this;
    }

}

