<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1/search.proto

namespace Search\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>search.v1.SearchProductsRequest</code>
 */
class SearchProductsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string text = 1 [json_name = "text"];</code>
     */
    protected $text = '';
    /**
     * Generated from protobuf field <code>repeated string categories = 2 [json_name = "categories"];</code>
     */
    private $categories;
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>.search.v1.Page page = 4 [json_name = "page"];</code>
     */
    protected $page = null;
    /**
     * Generated from protobuf field <code>.search.v1.RankingProfile ranking = 5 [json_name = "ranking"];</code>
     */
    protected $ranking = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $text
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $categories
     *     @type string $merchant_principal_id
     *     @type \Search\V1\Page $page
     *     @type int $ranking
     * }
     */
    public function __construct($data = NULL) {
        \Search\V1\GPBMetadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string text = 1 [json_name = "text"];</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 1 [json_name = "text"];</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string categories = 2 [json_name = "categories"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Generated from protobuf field <code>repeated string categories = 2 [json_name = "categories"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->categories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 3 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.search.v1.Page page = 4 [json_name = "page"];</code>
     * @return \Search\V1\Page|null
     */
    public function getPage()
    {
        return $this->page;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     * Generated from protobuf field <code>.search.v1.Page page = 4 [json_name = "page"];</code>
     * @param \Search\V1\Page $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Search\V1\Page::class);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.search.v1.RankingProfile ranking = 5 [json_name = "ranking"];</code>
     * @return int
     */
    public function getRanking()
    {
        return $this->ranking;
    }

    /**
     * Generated from protobuf field <code>.search.v1.RankingProfile ranking = 5 [json_name = "ranking"];</code>
     * @param int $var
     * @return $this
     */
    public function setRanking($var)
    {
        GPBUtil::checkEnum($var, \Search\V1\RankingProfile::class);
        $this->ranking = $var;

        return $this;
    }

}

