<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1/search.proto

namespace Search\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>search.v1.SuggestProductsResponse</code>
 */
class SuggestProductsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string suggestions = 1 [json_name = "suggestions"];</code>
     */
    private $suggestions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $suggestions
     * }
     */
    public function __construct($data = NULL) {
        \Search\V1\GPBMetadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string suggestions = 1 [json_name = "suggestions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSuggestions()
    {
        return $this->suggestions;
    }

    /**
     * Generated from protobuf field <code>repeated string suggestions = 1 [json_name = "suggestions"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSuggestions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->suggestions = $arr;

        return $this;
    }

}

