<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1/search.proto

namespace Search\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>search.v1.SuggestProductsRequest</code>
 */
class SuggestProductsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string prefix = 1 [json_name = "prefix"];</code>
     */
    protected $prefix = '';
    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $prefix
     *     @type int $limit
     * }
     */
    public function __construct($data = NULL) {
        \Search\V1\GPBMetadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string prefix = 1 [json_name = "prefix"];</code>
     * @return string
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Generated from protobuf field <code>string prefix = 1 [json_name = "prefix"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

