<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.GetMerchantInfoResponse</code>
 */
class GetMerchantInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     */
    protected $merchant_principal_id = '';
    /**
     * Generated from protobuf field <code>string store_name = 3 [json_name = "storeName"];</code>
     */
    protected $store_name = '';
    /**
     * Generated from protobuf field <code>string business_registration_number = 4 [json_name = "businessRegistrationNumber"];</code>
     */
    protected $business_registration_number = '';
    /**
     * Generated from protobuf field <code>string tax_id = 5 [json_name = "taxId"];</code>
     */
    protected $tax_id = '';
    /**
     * Generated from protobuf field <code>.identity.v1.MerchantStatus status = 6 [json_name = "status"];</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $merchant_principal_id
     *     @type string $store_name
     *     @type string $business_registration_number
     *     @type string $tax_id
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     * @return string
     */
    public function getMerchantPrincipalId()
    {
        return $this->merchant_principal_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_principal_id = 2 [json_name = "merchantPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string store_name = 3 [json_name = "storeName"];</code>
     * @return string
     */
    public function getStoreName()
    {
        return $this->store_name;
    }

    /**
     * Generated from protobuf field <code>string store_name = 3 [json_name = "storeName"];</code>
     * @param string $var
     * @return $this
     */
    public function setStoreName($var)
    {
        GPBUtil::checkString($var, True);
        $this->store_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string business_registration_number = 4 [json_name = "businessRegistrationNumber"];</code>
     * @return string
     */
    public function getBusinessRegistrationNumber()
    {
        return $this->business_registration_number;
    }

    /**
     * Generated from protobuf field <code>string business_registration_number = 4 [json_name = "businessRegistrationNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setBusinessRegistrationNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->business_registration_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tax_id = 5 [json_name = "taxId"];</code>
     * @return string
     */
    public function getTaxId()
    {
        return $this->tax_id;
    }

    /**
     * Generated from protobuf field <code>string tax_id = 5 [json_name = "taxId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTaxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tax_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantStatus status = 6 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantStatus status = 6 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Identity\V1\MerchantStatus::class);
        $this->status = $var;

        return $this;
    }

}

