<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.GetPrincipalResponse</code>
 */
class GetPrincipalResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     */
    protected $principal_id = '';
    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 3 [json_name = "kind"];</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>string display_name = 4 [json_name = "displayName"];</code>
     */
    protected $display_name = '';
    /**
     * Generated from protobuf field <code>repeated .identity.v1.ServiceLocalId aliases = 5 [json_name = "aliases"];</code>
     */
    private $aliases;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $principal_id
     *     @type int $kind
     *     @type string $display_name
     *     @type array<\Identity\V1\ServiceLocalId>|\Google\Protobuf\Internal\RepeatedField $aliases
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     * @return string
     */
    public function getPrincipalId()
    {
        return $this->principal_id;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 3 [json_name = "kind"];</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 3 [json_name = "kind"];</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Identity\V1\PrincipalKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_name = 4 [json_name = "displayName"];</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Generated from protobuf field <code>string display_name = 4 [json_name = "displayName"];</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .identity.v1.ServiceLocalId aliases = 5 [json_name = "aliases"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAliases()
    {
        return $this->aliases;
    }

    /**
     * Generated from protobuf field <code>repeated .identity.v1.ServiceLocalId aliases = 5 [json_name = "aliases"];</code>
     * @param array<\Identity\V1\ServiceLocalId>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAliases($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Identity\V1\ServiceLocalId::class);
        $this->aliases = $arr;

        return $this;
    }

}

