<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.GetUserProfileResponse</code>
 */
class GetUserProfileResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     */
    protected $principal_id = '';
    /**
     * Generated from protobuf field <code>string email = 3 [json_name = "email"];</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string full_name = 4 [json_name = "fullName"];</code>
     */
    protected $full_name = '';
    /**
     * Generated from protobuf field <code>string phone_number = 5 [json_name = "phoneNumber"];</code>
     */
    protected $phone_number = '';
    /**
     * Generated from protobuf field <code>string street_address = 6 [json_name = "streetAddress"];</code>
     */
    protected $street_address = '';
    /**
     * Generated from protobuf field <code>string city = 7 [json_name = "city"];</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string postal_code = 8 [json_name = "postalCode"];</code>
     */
    protected $postal_code = '';
    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 9 [json_name = "kind"];</code>
     */
    protected $kind = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $principal_id
     *     @type string $email
     *     @type string $full_name
     *     @type string $phone_number
     *     @type string $street_address
     *     @type string $city
     *     @type string $postal_code
     *     @type int $kind
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     * @return string
     */
    public function getPrincipalId()
    {
        return $this->principal_id;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3 [json_name = "email"];</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3 [json_name = "email"];</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string full_name = 4 [json_name = "fullName"];</code>
     * @return string
     */
    public function getFullName()
    {
        return $this->full_name;
    }

    /**
     * Generated from protobuf field <code>string full_name = 4 [json_name = "fullName"];</code>
     * @param string $var
     * @return $this
     */
    public function setFullName($var)
    {
        GPBUtil::checkString($var, True);
        $this->full_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone_number = 5 [json_name = "phoneNumber"];</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * Generated from protobuf field <code>string phone_number = 5 [json_name = "phoneNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string street_address = 6 [json_name = "streetAddress"];</code>
     * @return string
     */
    public function getStreetAddress()
    {
        return $this->street_address;
    }

    /**
     * Generated from protobuf field <code>string street_address = 6 [json_name = "streetAddress"];</code>
     * @param string $var
     * @return $this
     */
    public function setStreetAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->street_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 7 [json_name = "city"];</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 7 [json_name = "city"];</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 8 [json_name = "postalCode"];</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 8 [json_name = "postalCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postal_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 9 [json_name = "kind"];</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 9 [json_name = "kind"];</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Identity\V1\PrincipalKind::class);
        $this->kind = $var;

        return $this;
    }

}

