<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.MerchantRecord</code>
 */
class MerchantRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     */
    protected $principal_id = '';
    /**
     * Generated from protobuf field <code>string store_name = 2 [json_name = "storeName"];</code>
     */
    protected $store_name = '';
    /**
     * Generated from protobuf field <code>.identity.v1.MerchantStatus status = 3 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>bool may_sell = 4 [json_name = "maySell"];</code>
     */
    protected $may_sell = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 5 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $principal_id
     *     @type string $store_name
     *     @type int $status
     *     @type bool $may_sell
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @return string
     */
    public function getPrincipalId()
    {
        return $this->principal_id;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string store_name = 2 [json_name = "storeName"];</code>
     * @return string
     */
    public function getStoreName()
    {
        return $this->store_name;
    }

    /**
     * Generated from protobuf field <code>string store_name = 2 [json_name = "storeName"];</code>
     * @param string $var
     * @return $this
     */
    public function setStoreName($var)
    {
        GPBUtil::checkString($var, True);
        $this->store_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantStatus status = 3 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantStatus status = 3 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Identity\V1\MerchantStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool may_sell = 4 [json_name = "maySell"];</code>
     * @return bool
     */
    public function getMaySell()
    {
        return $this->may_sell;
    }

    /**
     * Generated from protobuf field <code>bool may_sell = 4 [json_name = "maySell"];</code>
     * @param bool $var
     * @return $this
     */
    public function setMaySell($var)
    {
        GPBUtil::checkBool($var);
        $this->may_sell = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 5 [json_name = "updatedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 5 [json_name = "updatedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

