<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.MerchantCursor</code>
 */
class MerchantCursor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     */
    protected $updated_through = null;
    /**
     * Generated from protobuf field <code>string last_principal_id = 2 [json_name = "lastPrincipalId"];</code>
     */
    protected $last_principal_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $updated_through
     *     @type string $last_principal_id
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedThrough()
    {
        return $this->updated_through;
    }

    public function hasUpdatedThrough()
    {
        return isset($this->updated_through);
    }

    public function clearUpdatedThrough()
    {
        unset($this->updated_through);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_through = 1 [json_name = "updatedThrough"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedThrough($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_through = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_principal_id = 2 [json_name = "lastPrincipalId"];</code>
     * @return string
     */
    public function getLastPrincipalId()
    {
        return $this->last_principal_id;
    }

    /**
     * Generated from protobuf field <code>string last_principal_id = 2 [json_name = "lastPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_principal_id = $var;

        return $this;
    }

}

