<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>identity.v1.MerchantStatus</code>
 */
class MerchantStatus
{
    /**
     * Generated from protobuf enum <code>MERCHANT_STATUS_UNSPECIFIED = 0;</code>
     */
    const MERCHANT_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>MERCHANT_STATUS_PENDING = 1;</code>
     */
    const MERCHANT_STATUS_PENDING = 1;
    /**
     * Generated from protobuf enum <code>MERCHANT_STATUS_VERIFIED = 2;</code>
     */
    const MERCHANT_STATUS_VERIFIED = 2;
    /**
     * Generated from protobuf enum <code>MERCHANT_STATUS_SUSPENDED = 3;</code>
     */
    const MERCHANT_STATUS_SUSPENDED = 3;
    /**
     * Generated from protobuf enum <code>MERCHANT_STATUS_CLOSED = 4;</code>
     */
    const MERCHANT_STATUS_CLOSED = 4;

    private static $valueToName = [
        self::MERCHANT_STATUS_UNSPECIFIED => 'MERCHANT_STATUS_UNSPECIFIED',
        self::MERCHANT_STATUS_PENDING => 'MERCHANT_STATUS_PENDING',
        self::MERCHANT_STATUS_VERIFIED => 'MERCHANT_STATUS_VERIFIED',
        self::MERCHANT_STATUS_SUSPENDED => 'MERCHANT_STATUS_SUSPENDED',
        self::MERCHANT_STATUS_CLOSED => 'MERCHANT_STATUS_CLOSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

