<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.MerchantsChangedSinceRequest</code>
 */
class MerchantsChangedSinceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.identity.v1.MerchantCursor cursor = 1 [json_name = "cursor"];</code>
     */
    protected $cursor = null;
    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Identity\V1\MerchantCursor $cursor
     *     @type int $limit
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantCursor cursor = 1 [json_name = "cursor"];</code>
     * @return \Identity\V1\MerchantCursor|null
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    public function hasCursor()
    {
        return isset($this->cursor);
    }

    public function clearCursor()
    {
        unset($this->cursor);
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantCursor cursor = 1 [json_name = "cursor"];</code>
     * @param \Identity\V1\MerchantCursor $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkMessage($var, \Identity\V1\MerchantCursor::class);
        $this->cursor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2 [json_name = "limit"];</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

