<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.MerchantsChangedSinceResponse</code>
 */
class MerchantsChangedSinceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .identity.v1.MerchantRecord upserted = 1 [json_name = "upserted"];</code>
     */
    private $upserted;
    /**
     * Generated from protobuf field <code>repeated string removed_principal_ids = 2 [json_name = "removedPrincipalIds"];</code>
     */
    private $removed_principal_ids;
    /**
     * Generated from protobuf field <code>.identity.v1.MerchantCursor next = 3 [json_name = "next"];</code>
     */
    protected $next = null;
    /**
     * Generated from protobuf field <code>bool has_more = 4 [json_name = "hasMore"];</code>
     */
    protected $has_more = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Identity\V1\MerchantRecord>|\Google\Protobuf\Internal\RepeatedField $upserted
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $removed_principal_ids
     *     @type \Identity\V1\MerchantCursor $next
     *     @type bool $has_more
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .identity.v1.MerchantRecord upserted = 1 [json_name = "upserted"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUpserted()
    {
        return $this->upserted;
    }

    /**
     * Generated from protobuf field <code>repeated .identity.v1.MerchantRecord upserted = 1 [json_name = "upserted"];</code>
     * @param array<\Identity\V1\MerchantRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUpserted($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Identity\V1\MerchantRecord::class);
        $this->upserted = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string removed_principal_ids = 2 [json_name = "removedPrincipalIds"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRemovedPrincipalIds()
    {
        return $this->removed_principal_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string removed_principal_ids = 2 [json_name = "removedPrincipalIds"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRemovedPrincipalIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->removed_principal_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantCursor next = 3 [json_name = "next"];</code>
     * @return \Identity\V1\MerchantCursor|null
     */
    public function getNext()
    {
        return $this->next;
    }

    public function hasNext()
    {
        return isset($this->next);
    }

    public function clearNext()
    {
        unset($this->next);
    }

    /**
     * Generated from protobuf field <code>.identity.v1.MerchantCursor next = 3 [json_name = "next"];</code>
     * @param \Identity\V1\MerchantCursor $var
     * @return $this
     */
    public function setNext($var)
    {
        GPBUtil::checkMessage($var, \Identity\V1\MerchantCursor::class);
        $this->next = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool has_more = 4 [json_name = "hasMore"];</code>
     * @return bool
     */
    public function getHasMore()
    {
        return $this->has_more;
    }

    /**
     * Generated from protobuf field <code>bool has_more = 4 [json_name = "hasMore"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHasMore($var)
    {
        GPBUtil::checkBool($var);
        $this->has_more = $var;

        return $this;
    }

}

