<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.ResolvePrincipalRequest</code>
 */
class ResolvePrincipalRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.identity.v1.ServiceLocalId service_local_id = 1 [json_name = "serviceLocalId"];</code>
     */
    protected $service_local_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Identity\V1\ServiceLocalId $service_local_id
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.identity.v1.ServiceLocalId service_local_id = 1 [json_name = "serviceLocalId"];</code>
     * @return \Identity\V1\ServiceLocalId|null
     */
    public function getServiceLocalId()
    {
        return $this->service_local_id;
    }

    public function hasServiceLocalId()
    {
        return isset($this->service_local_id);
    }

    public function clearServiceLocalId()
    {
        unset($this->service_local_id);
    }

    /**
     * Generated from protobuf field <code>.identity.v1.ServiceLocalId service_local_id = 1 [json_name = "serviceLocalId"];</code>
     * @param \Identity\V1\ServiceLocalId $var
     * @return $this
     */
    public function setServiceLocalId($var)
    {
        GPBUtil::checkMessage($var, \Identity\V1\ServiceLocalId::class);
        $this->service_local_id = $var;

        return $this;
    }

}

