<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.ServiceLocalId</code>
 */
class ServiceLocalId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service = 1 [json_name = "service"];</code>
     */
    protected $service = '';
    /**
     * Generated from protobuf field <code>string local_id = 2 [json_name = "localId"];</code>
     */
    protected $local_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service
     *     @type string $local_id
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string service = 1 [json_name = "service"];</code>
     * @return string
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>string service = 1 [json_name = "service"];</code>
     * @param string $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkString($var, True);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string local_id = 2 [json_name = "localId"];</code>
     * @return string
     */
    public function getLocalId()
    {
        return $this->local_id;
    }

    /**
     * Generated from protobuf field <code>string local_id = 2 [json_name = "localId"];</code>
     * @param string $var
     * @return $this
     */
    public function setLocalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->local_id = $var;

        return $this;
    }

}

