<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/v1/identity.proto

namespace Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>identity.v1.ValidateTokenResponse</code>
 */
class ValidateTokenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool valid = 1 [json_name = "valid"];</code>
     */
    protected $valid = false;
    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     */
    protected $principal_id = '';
    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 3 [json_name = "kind"];</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>string reason = 4 [json_name = "reason"];</code>
     */
    protected $reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $valid
     *     @type string $principal_id
     *     @type int $kind
     *     @type string $reason
     * }
     */
    public function __construct($data = NULL) {
        \Identity\V1\GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool valid = 1 [json_name = "valid"];</code>
     * @return bool
     */
    public function getValid()
    {
        return $this->valid;
    }

    /**
     * Generated from protobuf field <code>bool valid = 1 [json_name = "valid"];</code>
     * @param bool $var
     * @return $this
     */
    public function setValid($var)
    {
        GPBUtil::checkBool($var);
        $this->valid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     * @return string
     */
    public function getPrincipalId()
    {
        return $this->principal_id;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 2 [json_name = "principalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 3 [json_name = "kind"];</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.identity.v1.PrincipalKind kind = 3 [json_name = "kind"];</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Identity\V1\PrincipalKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 4 [json_name = "reason"];</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 4 [json_name = "reason"];</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

}

