<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>notification.v1.Channel</code>
 */
class Channel
{
    /**
     * Generated from protobuf enum <code>CHANNEL_UNSPECIFIED = 0;</code>
     */
    const CHANNEL_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>CHANNEL_PUSH = 1;</code>
     */
    const CHANNEL_PUSH = 1;
    /**
     * Generated from protobuf enum <code>CHANNEL_EMAIL = 2;</code>
     */
    const CHANNEL_EMAIL = 2;

    private static $valueToName = [
        self::CHANNEL_UNSPECIFIED => 'CHANNEL_UNSPECIFIED',
        self::CHANNEL_PUSH => 'CHANNEL_PUSH',
        self::CHANNEL_EMAIL => 'CHANNEL_EMAIL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

