<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>notification.v1.DeliveryStatus</code>
 */
class DeliveryStatus
{
    /**
     * Generated from protobuf enum <code>DELIVERY_STATUS_UNSPECIFIED = 0;</code>
     */
    const DELIVERY_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DELIVERY_STATUS_PENDING = 1;</code>
     */
    const DELIVERY_STATUS_PENDING = 1;
    /**
     * Generated from protobuf enum <code>DELIVERY_STATUS_SENT = 2;</code>
     */
    const DELIVERY_STATUS_SENT = 2;
    /**
     * Generated from protobuf enum <code>DELIVERY_STATUS_FAILED = 3;</code>
     */
    const DELIVERY_STATUS_FAILED = 3;
    /**
     * Generated from protobuf enum <code>DELIVERY_STATUS_UNREACHABLE = 4;</code>
     */
    const DELIVERY_STATUS_UNREACHABLE = 4;

    private static $valueToName = [
        self::DELIVERY_STATUS_UNSPECIFIED => 'DELIVERY_STATUS_UNSPECIFIED',
        self::DELIVERY_STATUS_PENDING => 'DELIVERY_STATUS_PENDING',
        self::DELIVERY_STATUS_SENT => 'DELIVERY_STATUS_SENT',
        self::DELIVERY_STATUS_FAILED => 'DELIVERY_STATUS_FAILED',
        self::DELIVERY_STATUS_UNREACHABLE => 'DELIVERY_STATUS_UNREACHABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

