<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notification.v1.DeliveryAttempt</code>
 */
class DeliveryAttempt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.notification.v1.Channel channel = 1 [json_name = "channel"];</code>
     */
    protected $channel = 0;
    /**
     * Generated from protobuf field <code>.notification.v1.DeliveryStatus status = 2 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int32 attempts = 3 [json_name = "attempts"];</code>
     */
    protected $attempts = 0;
    /**
     * Generated from protobuf field <code>string last_error = 4 [json_name = "lastError"];</code>
     */
    protected $last_error = '';
    /**
     * Generated from protobuf field <code>string last_attempt_at = 5 [json_name = "lastAttemptAt"];</code>
     */
    protected $last_attempt_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $channel
     *     @type int $status
     *     @type int $attempts
     *     @type string $last_error
     *     @type string $last_attempt_at
     * }
     */
    public function __construct($data = NULL) {
        \Notification\V1\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.notification.v1.Channel channel = 1 [json_name = "channel"];</code>
     * @return int
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.Channel channel = 1 [json_name = "channel"];</code>
     * @param int $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkEnum($var, \Notification\V1\Channel::class);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.DeliveryStatus status = 2 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.DeliveryStatus status = 2 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Notification\V1\DeliveryStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 attempts = 3 [json_name = "attempts"];</code>
     * @return int
     */
    public function getAttempts()
    {
        return $this->attempts;
    }

    /**
     * Generated from protobuf field <code>int32 attempts = 3 [json_name = "attempts"];</code>
     * @param int $var
     * @return $this
     */
    public function setAttempts($var)
    {
        GPBUtil::checkInt32($var);
        $this->attempts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_error = 4 [json_name = "lastError"];</code>
     * @return string
     */
    public function getLastError()
    {
        return $this->last_error;
    }

    /**
     * Generated from protobuf field <code>string last_error = 4 [json_name = "lastError"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastError($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_attempt_at = 5 [json_name = "lastAttemptAt"];</code>
     * @return string
     */
    public function getLastAttemptAt()
    {
        return $this->last_attempt_at;
    }

    /**
     * Generated from protobuf field <code>string last_attempt_at = 5 [json_name = "lastAttemptAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastAttemptAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_attempt_at = $var;

        return $this;
    }

}

