<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>notification.v1.DevicePlatform</code>
 */
class DevicePlatform
{
    /**
     * Generated from protobuf enum <code>DEVICE_PLATFORM_UNSPECIFIED = 0;</code>
     */
    const DEVICE_PLATFORM_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DEVICE_PLATFORM_ANDROID = 1;</code>
     */
    const DEVICE_PLATFORM_ANDROID = 1;
    /**
     * Generated from protobuf enum <code>DEVICE_PLATFORM_IOS = 2;</code>
     */
    const DEVICE_PLATFORM_IOS = 2;

    private static $valueToName = [
        self::DEVICE_PLATFORM_UNSPECIFIED => 'DEVICE_PLATFORM_UNSPECIFIED',
        self::DEVICE_PLATFORM_ANDROID => 'DEVICE_PLATFORM_ANDROID',
        self::DEVICE_PLATFORM_IOS => 'DEVICE_PLATFORM_IOS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

