<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notification.v1.ForgetDeviceResponse</code>
 */
class ForgetDeviceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool forgotten = 1 [json_name = "forgotten"];</code>
     */
    protected $forgotten = false;
    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 2 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $forgotten
     *     @type \Common\V1\ErrorDetail $error
     * }
     */
    public function __construct($data = NULL) {
        \Notification\V1\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool forgotten = 1 [json_name = "forgotten"];</code>
     * @return bool
     */
    public function getForgotten()
    {
        return $this->forgotten;
    }

    /**
     * Generated from protobuf field <code>bool forgotten = 1 [json_name = "forgotten"];</code>
     * @param bool $var
     * @return $this
     */
    public function setForgotten($var)
    {
        GPBUtil::checkBool($var);
        $this->forgotten = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 2 [json_name = "error"];</code>
     * @return \Common\V1\ErrorDetail|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.v1.ErrorDetail error = 2 [json_name = "error"];</code>
     * @param \Common\V1\ErrorDetail $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\ErrorDetail::class);
        $this->error = $var;

        return $this;
    }

}

