<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notification.v1.ForgetDeviceRequest</code>
 */
class ForgetDeviceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_token = 1 [json_name = "deviceToken"];</code>
     */
    protected $device_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_token
     * }
     */
    public function __construct($data = NULL) {
        \Notification\V1\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_token = 1 [json_name = "deviceToken"];</code>
     * @return string
     */
    public function getDeviceToken()
    {
        return $this->device_token;
    }

    /**
     * Generated from protobuf field <code>string device_token = 1 [json_name = "deviceToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_token = $var;

        return $this;
    }

}

