<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notification.v1.GetDeliveryResponse</code>
 */
class GetDeliveryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     */
    protected $found = false;
    /**
     * Generated from protobuf field <code>string notification_id = 2 [json_name = "notificationId"];</code>
     */
    protected $notification_id = '';
    /**
     * Generated from protobuf field <code>string recipient_principal_id = 3 [json_name = "recipientPrincipalId"];</code>
     */
    protected $recipient_principal_id = '';
    /**
     * Generated from protobuf field <code>.notification.v1.Template template = 4 [json_name = "template"];</code>
     */
    protected $template = 0;
    /**
     * Generated from protobuf field <code>repeated .notification.v1.DeliveryAttempt attempts = 5 [json_name = "attempts"];</code>
     */
    private $attempts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $found
     *     @type string $notification_id
     *     @type string $recipient_principal_id
     *     @type int $template
     *     @type array<\Notification\V1\DeliveryAttempt>|\Google\Protobuf\Internal\RepeatedField $attempts
     * }
     */
    public function __construct($data = NULL) {
        \Notification\V1\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @return bool
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * Generated from protobuf field <code>bool found = 1 [json_name = "found"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFound($var)
    {
        GPBUtil::checkBool($var);
        $this->found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notification_id = 2 [json_name = "notificationId"];</code>
     * @return string
     */
    public function getNotificationId()
    {
        return $this->notification_id;
    }

    /**
     * Generated from protobuf field <code>string notification_id = 2 [json_name = "notificationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setNotificationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->notification_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string recipient_principal_id = 3 [json_name = "recipientPrincipalId"];</code>
     * @return string
     */
    public function getRecipientPrincipalId()
    {
        return $this->recipient_principal_id;
    }

    /**
     * Generated from protobuf field <code>string recipient_principal_id = 3 [json_name = "recipientPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRecipientPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->recipient_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.Template template = 4 [json_name = "template"];</code>
     * @return int
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.Template template = 4 [json_name = "template"];</code>
     * @param int $var
     * @return $this
     */
    public function setTemplate($var)
    {
        GPBUtil::checkEnum($var, \Notification\V1\Template::class);
        $this->template = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .notification.v1.DeliveryAttempt attempts = 5 [json_name = "attempts"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttempts()
    {
        return $this->attempts;
    }

    /**
     * Generated from protobuf field <code>repeated .notification.v1.DeliveryAttempt attempts = 5 [json_name = "attempts"];</code>
     * @param array<\Notification\V1\DeliveryAttempt>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttempts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Notification\V1\DeliveryAttempt::class);
        $this->attempts = $arr;

        return $this;
    }

}

