<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notification.v1.GetDeliveryRequest</code>
 */
class GetDeliveryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string notification_id = 1 [json_name = "notificationId"];</code>
     */
    protected $notification_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $notification_id
     * }
     */
    public function __construct($data = NULL) {
        \Notification\V1\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string notification_id = 1 [json_name = "notificationId"];</code>
     * @return string
     */
    public function getNotificationId()
    {
        return $this->notification_id;
    }

    /**
     * Generated from protobuf field <code>string notification_id = 1 [json_name = "notificationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setNotificationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->notification_id = $var;

        return $this;
    }

}

