<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notification.v1.NotifyRequest</code>
 */
class NotifyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string recipient_principal_id = 1 [json_name = "recipientPrincipalId"];</code>
     */
    protected $recipient_principal_id = '';
    /**
     * Generated from protobuf field <code>.notification.v1.Template template = 2 [json_name = "template"];</code>
     */
    protected $template = 0;
    /**
     * Generated from protobuf field <code>map<string, string> params = 3 [json_name = "params"];</code>
     */
    private $params;
    /**
     * Generated from protobuf field <code>repeated .notification.v1.Channel channels = 4 [json_name = "channels"];</code>
     */
    private $channels;
    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     */
    protected $idempotency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $recipient_principal_id
     *     @type int $template
     *     @type array|\Google\Protobuf\Internal\MapField $params
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $channels
     *     @type \Common\V1\IdempotencyKey $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \Notification\V1\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string recipient_principal_id = 1 [json_name = "recipientPrincipalId"];</code>
     * @return string
     */
    public function getRecipientPrincipalId()
    {
        return $this->recipient_principal_id;
    }

    /**
     * Generated from protobuf field <code>string recipient_principal_id = 1 [json_name = "recipientPrincipalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRecipientPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->recipient_principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.Template template = 2 [json_name = "template"];</code>
     * @return int
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.Template template = 2 [json_name = "template"];</code>
     * @param int $var
     * @return $this
     */
    public function setTemplate($var)
    {
        GPBUtil::checkEnum($var, \Notification\V1\Template::class);
        $this->template = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> params = 3 [json_name = "params"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Generated from protobuf field <code>map<string, string> params = 3 [json_name = "params"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParams($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .notification.v1.Channel channels = 4 [json_name = "channels"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * Generated from protobuf field <code>repeated .notification.v1.Channel channels = 4 [json_name = "channels"];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChannels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Notification\V1\Channel::class);
        $this->channels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     * @return \Common\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Generated from protobuf field <code>.common.v1.IdempotencyKey idempotency_key = 5 [json_name = "idempotencyKey"];</code>
     * @param \Common\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\IdempotencyKey::class);
        $this->idempotency_key = $var;

        return $this;
    }

}

