<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notification.v1.RegisterDeviceRequest</code>
 */
class RegisterDeviceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     */
    protected $principal_id = '';
    /**
     * Generated from protobuf field <code>string device_token = 2 [json_name = "deviceToken"];</code>
     */
    protected $device_token = '';
    /**
     * Generated from protobuf field <code>.notification.v1.DevicePlatform platform = 3 [json_name = "platform"];</code>
     */
    protected $platform = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $principal_id
     *     @type string $device_token
     *     @type int $platform
     * }
     */
    public function __construct($data = NULL) {
        \Notification\V1\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @return string
     */
    public function getPrincipalId()
    {
        return $this->principal_id;
    }

    /**
     * Generated from protobuf field <code>string principal_id = 1 [json_name = "principalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_token = 2 [json_name = "deviceToken"];</code>
     * @return string
     */
    public function getDeviceToken()
    {
        return $this->device_token;
    }

    /**
     * Generated from protobuf field <code>string device_token = 2 [json_name = "deviceToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.DevicePlatform platform = 3 [json_name = "platform"];</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>.notification.v1.DevicePlatform platform = 3 [json_name = "platform"];</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkEnum($var, \Notification\V1\DevicePlatform::class);
        $this->platform = $var;

        return $this;
    }

}

