<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification.proto

namespace Notification\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>notification.v1.Template</code>
 */
class Template
{
    /**
     * Generated from protobuf enum <code>TEMPLATE_UNSPECIFIED = 0;</code>
     */
    const TEMPLATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>TEMPLATE_ORDER_PAID = 1;</code>
     */
    const TEMPLATE_ORDER_PAID = 1;
    /**
     * Generated from protobuf enum <code>TEMPLATE_ORDER_PACKED = 2;</code>
     */
    const TEMPLATE_ORDER_PACKED = 2;
    /**
     * Generated from protobuf enum <code>TEMPLATE_COURIER_ASSIGNED = 3;</code>
     */
    const TEMPLATE_COURIER_ASSIGNED = 3;
    /**
     * Generated from protobuf enum <code>TEMPLATE_ORDER_DELIVERED = 4;</code>
     */
    const TEMPLATE_ORDER_DELIVERED = 4;
    /**
     * Generated from protobuf enum <code>TEMPLATE_COURIER_OFFER = 5;</code>
     */
    const TEMPLATE_COURIER_OFFER = 5;
    /**
     * Generated from protobuf enum <code>TEMPLATE_RETURN_OPENED = 6;</code>
     */
    const TEMPLATE_RETURN_OPENED = 6;

    private static $valueToName = [
        self::TEMPLATE_UNSPECIFIED => 'TEMPLATE_UNSPECIFIED',
        self::TEMPLATE_ORDER_PAID => 'TEMPLATE_ORDER_PAID',
        self::TEMPLATE_ORDER_PACKED => 'TEMPLATE_ORDER_PACKED',
        self::TEMPLATE_COURIER_ASSIGNED => 'TEMPLATE_COURIER_ASSIGNED',
        self::TEMPLATE_ORDER_DELIVERED => 'TEMPLATE_ORDER_DELIVERED',
        self::TEMPLATE_COURIER_OFFER => 'TEMPLATE_COURIER_OFFER',
        self::TEMPLATE_RETURN_OPENED => 'TEMPLATE_RETURN_OPENED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

