<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/registry.proto

namespace Fleet\V1\GPBMetadata;

class Registry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Common\V1\GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCD\x07\x0A\x17fleet/v1/registry.proto\x12\x08fleet.v1\"\x80\x01\x0A\x15RegisterDriverRequest\x12!\x0A\x0Cprincipal_id\x18\x01 \x01(\x09R\x0BprincipalId\x12#\x0A\x0Dvehicle_plate\x18\x02 \x01(\x09R\x0CvehiclePlate\x12\x1F\x0A\x0Bcapacity_kg\x18\x03 \x01(\x05R\x0AcapacityKg\"\xAC\x01\x0A\x16RegisterDriverResponse\x12\x18\x0A\x07success\x18\x01 \x01(\x08R\x07success\x12\x1B\x0A\x09driver_id\x18\x02 \x01(\x03R\x08driverId\x12-\x0A\x12already_registered\x18\x03 \x01(\x08R\x11alreadyRegistered\x12,\x0A\x05error\x18\x04 \x01(\x0B2\x16.common.v1.ErrorDetailR\x05error\":\x0A\x15ActivateDriverRequest\x12!\x0A\x0Cprincipal_id\x18\x01 \x01(\x09R\x0BprincipalId\"\xA4\x01\x0A\x16ActivateDriverResponse\x12\x18\x0A\x07success\x18\x01 \x01(\x08R\x07success\x12\x1B\x0A\x09driver_id\x18\x02 \x01(\x03R\x08driverId\x12%\x0A\x0Ealready_active\x18\x03 \x01(\x08R\x0DalreadyActive\x12,\x0A\x05error\x18\x04 \x01(\x0B2\x16.common.v1.ErrorDetailR\x05error2\xC0\x01\x0A\x14FleetRegistryService\x12S\x0A\x0ERegisterDriver\x12\x1F.fleet.v1.RegisterDriverRequest\x1A .fleet.v1.RegisterDriverResponse\x12S\x0A\x0EActivateDriver\x12\x1F.fleet.v1.ActivateDriverRequest\x1A .fleet.v1.ActivateDriverResponseB\xC7\x01\x0A\x1Ecom.kinetix.contracts.fleet.v1B\x0DRegistryProtoP\x01ZCgithub.com/WildanFrananda/kinetix-contracts/gen/go/fleet/v1;fleetv1\xA2\x02\x03KNX\xAA\x02\x1AKinetix.Contracts.Fleet.V1\xCA\x02\x08Fleet\\V1\xE2\x02\x14Fleet\\V1\\GPBMetadata\xEA\x02\x09Fleet::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

