<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo/v1/geo.proto

namespace Geo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>geo.v1.GeocodeAddressRequest</code>
 */
class GeocodeAddressRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.v1.Address address = 1 [json_name = "address"];</code>
     */
    protected $address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Common\V1\Address $address
     * }
     */
    public function __construct($data = NULL) {
        \Geo\V1\GPBMetadata\Geo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address address = 1 [json_name = "address"];</code>
     * @return \Common\V1\Address|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.common.v1.Address address = 1 [json_name = "address"];</code>
     * @param \Common\V1\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\Address::class);
        $this->address = $var;

        return $this;
    }

}

