<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo/v1/geo.proto

namespace Geo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>geo.v1.GeocodeAddressesRequest</code>
 */
class GeocodeAddressesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .common.v1.Address addresses = 1 [json_name = "addresses"];</code>
     */
    private $addresses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Common\V1\Address>|\Google\Protobuf\Internal\RepeatedField $addresses
     * }
     */
    public function __construct($data = NULL) {
        \Geo\V1\GPBMetadata\Geo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .common.v1.Address addresses = 1 [json_name = "addresses"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .common.v1.Address addresses = 1 [json_name = "addresses"];</code>
     * @param array<\Common\V1\Address>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\V1\Address::class);
        $this->addresses = $arr;

        return $this;
    }

}

