<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo/v1/geo.proto

namespace Geo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>geo.v1.GeocodeAddressesResponse</code>
 */
class GeocodeAddressesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .geo.v1.GeocodeAddressResponse results = 1 [json_name = "results"];</code>
     */
    private $results;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Geo\V1\GeocodeAddressResponse>|\Google\Protobuf\Internal\RepeatedField $results
     * }
     */
    public function __construct($data = NULL) {
        \Geo\V1\GPBMetadata\Geo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .geo.v1.GeocodeAddressResponse results = 1 [json_name = "results"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * Generated from protobuf field <code>repeated .geo.v1.GeocodeAddressResponse results = 1 [json_name = "results"];</code>
     * @param array<\Geo\V1\GeocodeAddressResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Geo\V1\GeocodeAddressResponse::class);
        $this->results = $arr;

        return $this;
    }

}

