<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo/v1/geo.proto

namespace Geo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>geo.v1.GeocodeAddressResponse</code>
 */
class GeocodeAddressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool geocoded = 1 [json_name = "geocoded"];</code>
     */
    protected $geocoded = false;
    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint location = 2 [json_name = "location"];</code>
     */
    protected $location = null;
    /**
     * Generated from protobuf field <code>.geo.v1.GeocodeFailure failure = 3 [json_name = "failure"];</code>
     */
    protected $failure = 0;
    /**
     * Generated from protobuf field <code>string failure_detail = 4 [json_name = "failureDetail"];</code>
     */
    protected $failure_detail = '';
    /**
     * Generated from protobuf field <code>.geo.v1.GeocodePrecision precision = 5 [json_name = "precision"];</code>
     */
    protected $precision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $geocoded
     *     @type \Common\V1\GeoPoint $location
     *     @type int $failure
     *     @type string $failure_detail
     *     @type int $precision
     * }
     */
    public function __construct($data = NULL) {
        \Geo\V1\GPBMetadata\Geo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool geocoded = 1 [json_name = "geocoded"];</code>
     * @return bool
     */
    public function getGeocoded()
    {
        return $this->geocoded;
    }

    /**
     * Generated from protobuf field <code>bool geocoded = 1 [json_name = "geocoded"];</code>
     * @param bool $var
     * @return $this
     */
    public function setGeocoded($var)
    {
        GPBUtil::checkBool($var);
        $this->geocoded = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint location = 2 [json_name = "location"];</code>
     * @return \Common\V1\GeoPoint|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    public function hasLocation()
    {
        return isset($this->location);
    }

    public function clearLocation()
    {
        unset($this->location);
    }

    /**
     * Generated from protobuf field <code>.common.v1.GeoPoint location = 2 [json_name = "location"];</code>
     * @param \Common\V1\GeoPoint $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Common\V1\GeoPoint::class);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.geo.v1.GeocodeFailure failure = 3 [json_name = "failure"];</code>
     * @return int
     */
    public function getFailure()
    {
        return $this->failure;
    }

    /**
     * Generated from protobuf field <code>.geo.v1.GeocodeFailure failure = 3 [json_name = "failure"];</code>
     * @param int $var
     * @return $this
     */
    public function setFailure($var)
    {
        GPBUtil::checkEnum($var, \Geo\V1\GeocodeFailure::class);
        $this->failure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string failure_detail = 4 [json_name = "failureDetail"];</code>
     * @return string
     */
    public function getFailureDetail()
    {
        return $this->failure_detail;
    }

    /**
     * Generated from protobuf field <code>string failure_detail = 4 [json_name = "failureDetail"];</code>
     * @param string $var
     * @return $this
     */
    public function setFailureDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->failure_detail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.geo.v1.GeocodePrecision precision = 5 [json_name = "precision"];</code>
     * @return int
     */
    public function getPrecision()
    {
        return $this->precision;
    }

    /**
     * Generated from protobuf field <code>.geo.v1.GeocodePrecision precision = 5 [json_name = "precision"];</code>
     * @param int $var
     * @return $this
     */
    public function setPrecision($var)
    {
        GPBUtil::checkEnum($var, \Geo\V1\GeocodePrecision::class);
        $this->precision = $var;

        return $this;
    }

}

