<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo/v1/geo.proto

namespace Geo\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>geo.v1.GeocodeFailure</code>
 */
class GeocodeFailure
{
    /**
     * Generated from protobuf enum <code>GEOCODE_FAILURE_UNSPECIFIED = 0;</code>
     */
    const GEOCODE_FAILURE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>GEOCODE_FAILURE_NOT_FOUND = 1;</code>
     */
    const GEOCODE_FAILURE_NOT_FOUND = 1;
    /**
     * Generated from protobuf enum <code>GEOCODE_FAILURE_AMBIGUOUS = 2;</code>
     */
    const GEOCODE_FAILURE_AMBIGUOUS = 2;
    /**
     * Generated from protobuf enum <code>GEOCODE_FAILURE_PROVIDER_UNAVAILABLE = 3;</code>
     */
    const GEOCODE_FAILURE_PROVIDER_UNAVAILABLE = 3;
    /**
     * Generated from protobuf enum <code>GEOCODE_FAILURE_OUT_OF_SERVICE_AREA = 4;</code>
     */
    const GEOCODE_FAILURE_OUT_OF_SERVICE_AREA = 4;
    /**
     * Generated from protobuf enum <code>GEOCODE_FAILURE_INSUFFICIENT_ADDRESS = 5;</code>
     */
    const GEOCODE_FAILURE_INSUFFICIENT_ADDRESS = 5;

    private static $valueToName = [
        self::GEOCODE_FAILURE_UNSPECIFIED => 'GEOCODE_FAILURE_UNSPECIFIED',
        self::GEOCODE_FAILURE_NOT_FOUND => 'GEOCODE_FAILURE_NOT_FOUND',
        self::GEOCODE_FAILURE_AMBIGUOUS => 'GEOCODE_FAILURE_AMBIGUOUS',
        self::GEOCODE_FAILURE_PROVIDER_UNAVAILABLE => 'GEOCODE_FAILURE_PROVIDER_UNAVAILABLE',
        self::GEOCODE_FAILURE_OUT_OF_SERVICE_AREA => 'GEOCODE_FAILURE_OUT_OF_SERVICE_AREA',
        self::GEOCODE_FAILURE_INSUFFICIENT_ADDRESS => 'GEOCODE_FAILURE_INSUFFICIENT_ADDRESS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

